// 面试题库 · 算法 C 卷：位运算 / 数学 / 海量数据 / 复杂度分析 / 编码与工程。
// 本文件是「面试刷题」工具的离线题库数据源之一，只导出纯数据、无副作用，由工具页按 topic / difficulty / tags 过滤渲染，用于自测自评。
// 定位是「A 卷数据结构、B 卷算法范式」之外的补充：这一卷考的是容易被忽略但面试常问的底层基本功——
// 位技巧与状态压缩、数论与取模、内存放不下时的工程解法、复杂度怎么算、以及白板上的沟通习惯。
// 出处约定：每条题目的 sources 标注参考答案的来源仓库与仓库内相对路径，repo 只能取固定枚举
// （leetcode-master / hello-algo / fucking-algorithm / azl397985856-leetcode / CS-Notes），path 必须是该仓库里真实存在的前缀，仅作学习引用。
export const ALGO_C_QUESTIONS = [
  {
    id: "algo-c-bit-tricks",
    category: "algo",
    topic: "位运算",
    difficulty: 1,
    tags: ["位运算", "lowbit", "二进制"],
    question: "lowbit、判断 2 的幂、统计二进制里 1 的个数，这三个技巧分别怎么写",
    answer: "lowbit 是 x 与负 x 做按位与，得到只保留最低位那个 1 的数，树状数组靠它定位。判断 2 的幂用 x 大于 0 且 x 与 x 减一 的按位与为 0：2 的幂只有一位是 1，减一会让这一位变 0、低位全变 1，按位与必然为 0。统计 1 的个数则反复执行 x 与 x 减一，每次抹掉最低位的 1，循环几次就有几个 1，比逐位移位快得多。\n- 时间 O(1)、O(k)。\n- 空间 O(1)。\n易错点：判断 2 的幂必须先排除 0，否则条件会假成立；负数在补码下 lowbit 同样成立，但移位要用无符号右移，否则会补符号位。\n```python\nlowbit = x & -x\nis_pow2 = x > 0 and x & (x - 1) == 0\ncnt = 0\nwhile x:\n    x &= x - 1\n    cnt += 1\n```",
    points: ["lowbit 取最低位的 1", "x 与 x 减一 抹掉最低位的 1", "判断 2 的幂要先排除 0"],
    follow: "如果是判断 4 的幂，或者要统计最高位的 1，思路怎么变",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-c-bit-single-number",
    category: "algo",
    topic: "位运算",
    difficulty: 2,
    tags: ["异或", "只出现一次", "分组"],
    question: "只出现一次的数字：其余都出现两次怎么找，如果两个数都只出现一次呢",
    answer: "异或有三条性质：自己异或自己是 0，任何数与 0 异或是它本身，且满足交换律和结合律。所以把数组全部异或起来，成对出现的数字互相抵消，剩下的就是只出现一次的那个数。\n两个数都只出现一次时，先求全体异或值 x，它是这两个数的异或值，一定不为 0，取 lowbit 就找到一个两数必然不同的二进制位。按这一位是不是 1 把数组分成两组，两个目标数必然分在两边，组内各自异或就得到答案。\n- 时间 O(n)，空间 O(1)。\n易错点：lowbit 用 x 与负 x 求；分组标准必须来自全体异或值；如果其余数字出现三次，异或失效，要改成按二进制位统计余数。\n```python\nlow = x & -x\na = b = 0\nfor v in nums:\n    if v & low:\n        a ^= v\n    else:\n        b ^= v\n```",
    points: ["异或满足交换律，成对的互相抵消", "全体异或得到两个目标数的异或值", "按最低位的 1 分组再各自异或"],
    follow: "如果其余数字都出现三次，异或就不够用了，怎么改",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-c-bit-subset-enum",
    category: "algo",
    topic: "位运算",
    difficulty: 3,
    tags: ["状态压缩", "子集枚举", "位掩码"],
    question: "怎么用位运算枚举一个集合的所有子集，以及枚举某个掩码的所有子集",
    answer: "状态压缩把一个集合塞进一个整数的二进制位：第 i 位是 1 表示选了第 i 个元素。于是从 0 枚举到 2 的 n 次方减 1，就恰好遍历所有子集，判断某一位用掩码右移 i 再与 1。状压 DP 的转移就是枚举上一个掩码。\n枚举某个掩码的所有子集，用子集减一 再与掩码：减一会借走最低位的 1，相与就跳过不属于掩码的位，能走完所有子集并停在 0。\n- 时间 O(2 的 n 次方)，枚举子集的子集共 O(3 的 n 次方)。\n易错点：n 超过 30 时 1 左移 n 会溢出 int；循环里必须先减再与，写反会死循环。\n```python\nfor mask in range(1 << n):\n    if mask >> i & 1:\n        use(i)\nsub = mask\nwhile sub:\n    use(sub)\n    sub = (sub - 1) & mask\n```",
    points: ["整数每一位代表一个元素选不选", "从零枚举到二的 n 次方减一", "子集减一后与掩码得到下一个子集"],
    follow: "枚举所有子集的子集，总复杂度为什么是 3 的 n 次方",
    sources: [{ repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-c-math-fast-power",
    category: "algo",
    topic: "数学",
    difficulty: 2,
    tags: ["快速幂", "取模", "溢出"],
    question: "快速幂怎么实现，取模的时候要注意哪些溢出问题",
    answer: "快速幂把指数按二进制拆开：a 的 n 次方等于 a 的 1、2、4……次方里 n 的二进制为 1 的那些项的乘积。底数每轮自乘就翻倍，指数每轮右移一位，当前位是 1 就把底数乘进结果，只要 O(log n) 次乘法。\n取模要贯穿始终：底数先取模，每乘一次立刻取模，中间值才不会被撑爆。\n- 时间 O(log n)，空间 O(1)。\n易错点：指数为 0 要返回 1 对模数取模；指数为负要先转成逆元，模数是质数才能用费马小定理；Java 里两个接近模数的数相乘会超出 long，要用 128 位中间量。\n```python\ndef power(a, n, mod):\n    r = 1\n    while n:\n        if n & 1: r = r * a % mod\n        a = a * a % mod\n        n >>= 1\n    return r\n```",
    points: ["指数按二进制拆开，底数不断平方", "底数先取模，每次乘完立刻取模", "两个大数相乘会溢出，要龟速乘"],
    follow: "指数是负数，或者模数不是质数时，快速幂怎么调整",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-c-math-gcd-euclid",
    category: "algo",
    topic: "数学",
    difficulty: 3,
    tags: ["最大公约数", "欧几里得", "贝祖系数"],
    question: "欧几里得求最大公约数的原理是什么，扩展欧几里得又多求了什么",
    answer: "欧几里得的依据是 gcd(a, b) 等于 gcd(b, a 对 b 取模)：设 a 等于 q 乘 b 加 r，能同时整除 a 和 b 的数必然整除 r，反过来也成立，所以公约数集合相同，最大公约数相等。递归到第二个参数为 0 时，第一个参数即答案。\n扩展欧几里得在回溯时求出一组满足 a 乘 x 加 b 乘 y 等于 gcd 的整数解，即贝祖系数，可用来求模逆元和解同余方程。\n- 时间 O(log n)，空间 O(log n)。\n易错点：负数先取绝对值算；取模的符号在 C++ 和 Java 里跟着被除数走；求逆元前必须确认 gcd 等于 1。\n```python\ndef egcd(a, b):\n    if b == 0: return a, 1, 0\n    g, x, y = egcd(b, a % b)\n    return g, y, x - a // b * y\n```",
    points: ["gcd 等于第二参数与取模的 gcd", "取模前后公约数集合不变", "扩展版回溯时求出贝祖系数"],
    follow: "怎么用扩展欧几里得求一个数在模意义下的逆元",
    sources: [{ repo: "CS-Notes", path: "docs/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-c-math-prime-sieve",
    category: "algo",
    topic: "数学",
    difficulty: 2,
    tags: ["质数筛", "线性筛", "质因数分解"],
    question: "埃氏筛和线性筛的区别在哪，质因数分解又该怎么做",
    answer: "埃氏筛从 2 开始，遇到质数就把它的倍数标记成合数，没被标记的就是质数；内层从 i 乘 i 开始，更小的倍数已被筛过。\n线性筛维护最小质因数，每个合数只被最小质因数筛掉一次，所以是严格 O(n)：内层标记 i 乘 p，p 能整除 i 就跳出。\n分解用试除法：从 2 试到根号 n，能整除就除干净，剩下的数大于 1 时它本身就是质数。\n- 时间：埃氏筛 O(n log log n)，线性筛 O(n)。\n易错点：埃氏筛从 i 乘 i 开始的前提是它不超过 n；线性筛跳出位置写错会重复标记；试除条件别写成 i 小于 n。\n```python\nok = [True] * (n + 1)\nfor i in range(2, int(n ** 0.5) + 1):\n    if ok[i]:\n        ok[i*i::i] = [False] * len(ok[i*i::i])\n```",
    points: ["埃氏筛标记每个质数的倍数", "线性筛保证合数只被筛一次", "分解时试除到根号 n 即可"],
    follow: "如果要筛一个区间内的质数而不是从 2 开始的，筛法怎么改",
    sources: [{ repo: "CS-Notes", path: "docs/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-c-bigdata-bitmap",
    category: "algo",
    topic: "海量数据",
    difficulty: 2,
    tags: ["位图", "海量数据", "内存限制"],
    question: "40 亿个不重复整数，内存只有几百兆，怎么判断某个数是否存在",
    answer: "位图用一个二进制位表示一个数在不在：第 k 位是 1 就表示数 k 出现过。40 亿个不重复整数最多要 40 亿位，约 500 兆字节，正好卡在题目给的内存里，比 int 数组省 32 倍。\n实现上用 bytearray 或 long 数组：数除以 8 得到下标，对 8 取模得到位偏移，置位是按位或，查询是与上那一位。\n- 时间 O(1)，空间 O(范围除以 8)。\n易错点：动手前先问清数值范围，范围大但稀疏时位图反而浪费，该用哈希或布隆过滤器；位图只记录存在性，要计数得用多位；范围超过 32 位时下标要用 long。\n```python\nb = bytearray(limit // 8 + 1)\ndef add(x):\n    b[x >> 3] |= 1 << (x & 7)\ndef has(x):\n    return b[x >> 3] >> (x & 7) & 1\n```",
    points: ["每一位代表一个数在不在", "四十亿位约等于五百兆字节", "先确认数值范围再选结构"],
    follow: "如果允许百分之一的误判，还有什么更省内存的方案",
    sources: [{ repo: "CS-Notes", path: "docs/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-c-bigdata-topk-heap",
    category: "algo",
    topic: "海量数据",
    difficulty: 3,
    tags: ["TopK", "小顶堆", "分治"],
    question: "10 亿个数里找最大的 100 个，内存放不下，怎么做",
    answer: "标准解法是分治加堆。先用哈希把 10 亿个数散到若干小文件，同一个数只进同一个文件，每个小文件都小到能读进内存；再对每个文件维护一个大小为 K 的小顶堆，堆顶是这 K 个里最小的，新元素比堆顶大就替换并下沉；最后合并各文件的堆取前 K。\n- 时间 O(N log K)，空间 O(K) 加一个桶。\n易错点：求最大的 K 个要用小顶堆，大顶堆会把最大的挤出去；分桶要均匀，否则某个桶仍然放不下；数据能全放进内存时直接一个堆扫一遍即可。\n```python\nimport heapq\n\nh = []\nfor v in stream:\n    if len(h) < k:\n        heapq.heappush(h, v)\n    elif v > h[0]:\n        heapq.heapreplace(h, v)\n```",
    points: ["求最大的 K 个要用小顶堆", "堆顶是当前 K 个里最小的", "先哈希分桶，各桶分别求 TopK"],
    follow: "如果改成求出现次数最多的 100 个词，流程要怎么调整",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-c-bigdata-common-url",
    category: "algo",
    topic: "海量数据",
    difficulty: 3,
    tags: ["哈希分桶", "海量数据", "去重"],
    question: "两个各 100G 的文件里存着 URL，怎么找出它们共同的 URL",
    answer: "大文件放不进内存，就把它拆成一批小文件，关键是保证相同的 URL 一定落到同一对小文件里。做法是对 URL 求哈希，用哈希值对桶数取模决定归属；两个文件用同一个哈希函数和桶数，第 i 个小文件只需和第 i 个比较。\n逐对处理时，把一个桶的 URL 读进哈希表，再遍历另一边的桶查表，命中的就是共同 URL。只要去重或判存在，换成布隆过滤器还能更省内存。\n- 时间 O(N)，空间 O(N 除以桶数)，由桶数控制。\n易错点：桶数按可用内存反推，必须保证单个桶装得下；两边哈希函数不一致会得到完全错误的结果；只存哈希值时要意识到碰撞会误判。\n```python\nimport hashlib\n\ndef bucket_of(url, n):\n    h = hashlib.md5(url.encode()).hexdigest()\n    return int(h, 16) % n\n```",
    points: ["按哈希取模把大文件拆成小文件", "相同 URL 必然落到同一对桶", "桶数按可用内存反推"],
    follow: "如果要求出重复次数最多的那个 URL，思路还要加什么",
    sources: [{ repo: "CS-Notes", path: "docs/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-c-complexity-growth",
    category: "algo",
    topic: "复杂度分析",
    difficulty: 1,
    tags: ["复杂度", "主定理", "增长量级"],
    question: "常见时间复杂度怎么直观对照，主定理又怎么快速估算分治的复杂度",
    answer: "把 n 取十万来对照：O(1)、O(log n) 是一瞬间，log 十万约十七次；O(n) 是十万次操作，毫秒级；O(n log n) 约一百七十万次，是排序算法的分水岭；O(n 的平方) 是一百亿次，不可接受。\n主定理用来估算分治：把递归写成 T(n) 等于 a 乘 T(n 除以 b) 加 f(n)，比较合并代价 f(n) 与叶子代价 n 的 log 以 b 为底 a 次方。合并代价更小就取叶子代价，归并排序是 n log n，二分查找是 log n；同阶就再乘一个 log n。\n易错点：主定理要求子问题规模相等且 a、b 是常数，每次只减一的递归不适用，改用递归树或代入法。\n```text\nO(log n)   约 17 次\nO(n)       10 万次\nO(n log n) 170 万次\nO(n^2)     100 亿次\nO(2^n)     n 到 20 就爆\n```",
    points: ["按十万规模对照各量级的操作次数", "n log n 是排序类算法的分水岭", "主定理比较合并代价与叶子代价"],
    follow: "为什么 O(n log n) 被当作通用比较排序的下界",
    sources: [{ repo: "hello-algo", path: "docs/chapter_computational_complexity/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-c-complexity-amortized",
    category: "algo",
    topic: "复杂度分析",
    difficulty: 3,
    tags: ["均摊分析", "并查集", "路径压缩"],
    question: "均摊复杂度是什么意思，并查集的路径压缩为什么算均摊而不是单次",
    answer: "均摊是把一串操作的总代价平摊到每次操作，衡量的是操作序列的平均代价，而不是单次最坏代价，所以「最坏 O(n)、均摊 O(1)」并不矛盾。动态数组按倍数扩容：n 次追加的总搬运量不超过 2n，所以追加均摊 O(1)，触发扩容那一次是 O(n)。\n并查集同理。只用路径压缩时单次 find 最坏仍是 O(n)，但 m 次操作总代价是 O(m log n)，均摊接近常数；再加按秩合并，总代价降到 O(m 乘 α(n))，α 是反阿克曼函数，实际规模里不超过 5。\n易错点：均摊的界只能对操作序列承诺；扩容改成每次加固定大小会退化成 O(n 的平方)。\n```python\ndef find(x):\n    while parent[x] != x:\n        parent[x] = parent[parent[x]]\n        x = parent[x]\n    return x\n```",
    points: ["均摊是操作序列的平均代价", "扩容总搬运量不超过二 n", "路径压缩加按秩合并接近常数"],
    follow: "势能分析法是怎么把路径压缩的代价算清楚的",
    sources: [{ repo: "hello-algo", path: "docs/chapter_computational_complexity/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-c-complexity-recursion-space",
    category: "algo",
    topic: "复杂度分析",
    difficulty: 2,
    tags: ["递归", "空间复杂度", "调用栈"],
    question: "递归的空间复杂度怎么算，为什么快排是 O(log n) 而不是 O(n)",
    answer: "递归的空间开销主要来自调用栈，每层要保存参数、局部变量和返回地址，所以空间复杂度等于最大递归深度乘每层开销，而不是调用总次数，也不是递归树的分支数。\n快排平均把区间对半分，深度 log n，空间 O(log n)；但划分极不均匀时（如数组已有序而基准取第一个），深度退化成 n，空间就是 O(n)。归并排序深度恒为 log n，空间 O(log n)，但它合并要开长度 n 的临时数组，总空间才是 O(n)。\n易错点：分支数不影响空间，深度才影响，二叉树遍历 n 个节点，空间只有 O(树高)；每层都开长度 n 的数组就是 O(n log n)。\n```python\ndef qs(a, lo, hi):\n    if lo >= hi: return\n    p = part(a, lo, hi)\n    qs(a, lo, p - 1)\n    qs(a, p + 1, hi)\n```",
    points: ["空间由最大递归深度决定", "分支数不影响空间，深度才影响", "每层开数组会把空间乘上深度"],
    follow: "尾递归为什么能优化成常数空间，Java 支持吗",
    sources: [{ repo: "hello-algo", path: "docs/chapter_computational_complexity/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-c-eng-binary-search",
    category: "algo",
    topic: "编码与工程",
    difficulty: 2,
    tags: ["二分查找", "边界", "白板编码"],
    question: "白板手写二分查找，面试官最常抓的几个错误是什么",
    answer: "写二分第一步是把区间定义说清楚，后面所有边界都由它推出来。左闭右闭时循环条件是 left 小于等于 right，中点写 left 加 right 减 left 的一半，缩区间时 mid 已比较过，更新成 mid 加一或 mid 减一；左闭右开时循环条件是小于，右边界更新成 mid，初值取长度。\n- 时间 O(log n)，空间 O(1)。\n常见失分点：中点写成两数相加再整除 2 会整数溢出；缩区间漏掉加减一会死循环；两种区间写法混用会让区间永远不缩小；找不到时的返回值没先约定；忘了空数组。\n```python\nlo, hi = 0, len(nums)\nwhile lo < hi:\n    mid = lo + (hi - lo) // 2\n    if nums[mid] < target: lo = mid + 1\n    else: hi = mid\nreturn lo\n```",
    points: ["先说清区间是左闭右闭还是左闭右开", "中点用左界加差值的一半防溢出", "缩区间漏掉加减一会死循环"],
    follow: "如果要找第一个大于等于目标的元素，边界该怎么写",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_searching/" }],
  },
  {
    id: "algo-c-eng-communication",
    category: "algo",
    topic: "编码与工程",
    difficulty: 1,
    tags: ["面试沟通", "白板编码", "解题流程"],
    question: "面试时拿到一道算法题，从读题到写完的完整流程该怎么走",
    answer: "拿到题先别写代码，把流程走完再动手，面试官打的分里有相当一部分是沟通和工程习惯。\n- 复述题意：用自己的话说一遍输入输出，追问数据规模、取值范围、有没有重复、要不要处理空输入。规模决定算法，n 是一千还是一千万，答案完全不同。\n- 说思路再动手：给两三个可行方案，逐个报时间与空间复杂度，说明为什么选这个，再问是否可以开始写。直接闷头写反而像背过题。\n- 边写边说：变量名取有意义的，把不变量讲出来，比如「这里维护的是前 i 个元素的最大值」。卡住时说出困惑，别沉默。\n- 写完自测：主动造小例子手动跑一遍，覆盖空输入、单个元素、全部相同、边界值。发现 bug 要说明原因再改，不要悄悄改掉。\n- 收尾：主动说最终复杂度和可能的优化方向。\n```text\n复述题意 -> 说思路与复杂度 -> 确认后动手 -> 边写边说 -> 举例自测 -> 总结优化\n```",
    points: ["先复述题意，确认边界与数据规模", "说两三个思路并比较复杂度再动手", "写完用小例子和边界自测一遍"],
    follow: "如果完全没思路，怎么和面试官要提示又不显得放弃",
    sources: [{ repo: "CS-Notes", path: "docs/" }, { repo: "fucking-algorithm", path: "技术/" }],
  },
];
