// 面试题库 · 算法与数据结构。
// 本文件是「面试刷题」工具的离线题库数据源，只导出纯数据、无副作用，由工具页按 topic / difficulty / tags 过滤渲染，用于自测自评。
// 出处约定：每条题目的 sources 标注参考答案的来源仓库与仓库内相对路径，repo 只能取固定枚举
// （leetcode-master / hello-algo / fucking-algorithm / azl397985856-leetcode / CS-Notes），path 必须是该仓库里真实存在的前缀，仅作学习引用。
export const ALGO_QUESTIONS = [
  {
    id: "algo-array-two-sum",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 1,
    tags: ["数组", "哈希表", "双指针"],
    question: "两数之和：哈希表为什么能把时间复杂度降到 O(n)",
    answer: "暴力枚举每一对数要 O(n²)。换个角度想：遍历到 nums[i] 时，我真正关心的是「target 减 nums[i] 这个值之前出现过吗」，把「值到下标的映射」存进哈希表，一次查询就是均摊 O(1)。\n- 时间 O(n)：每个元素只进出哈希表一次，单次代价均摊 O(1)。\n- 空间 O(n)：最坏情况所有元素都要存下来。\n易错点：必须**先查再存**，否则 target 正好等于两倍 nums[i] 时会把同一个元素用两次；如果数组有序、只要求返回值而不要求原下标，可以用双指针把空间降到 O(1)，但排序会打乱下标，这点要先和面试官确认。\n```python\ndef two_sum(nums, target):\n    seen = dict()\n    for i, v in enumerate(nums):\n        if target - v in seen:\n            return [seen[target - v], i]\n        seen[v] = i\n    return []\n```",
    points: ["先说清暴力 O(n²) 慢在哪", "哈希表存值到下标的映射", "强调先查再存，避免自匹配"],
    follow: "如果数组已经有序，并且要求 O(1) 额外空间，怎么做",
    sources: [{ repo: "leetcode-master", path: "problems/0001.两数之和.md" }, { repo: "hello-algo", path: "docs/chapter_hashing/" }],
  },
  {
    id: "algo-array-three-sum",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 2,
    tags: ["数组", "双指针", "排序", "去重"],
    question: "LeetCode 15 三数之和：怎么做到不重不漏",
    answer: "先排序，再固定一个数 nums[i]，剩下两个数用左右指针夹逼：和偏小就左指针右移，偏大就右指针左移。排序让「该动哪一边」有了确定方向，这是双指针能成立的前提。\n- 时间 O(n²)：外层枚举 n 次，内层双指针最多走 n 步；排序的 O(n log n) 被吸收。\n- 空间 O(1)：不计排序和结果，只用常数个指针。\n去重是唯一难点，三处都要处理：i 与前一个值相同就跳过；找到一组解后左右指针都要跳过重复值；跳过用 while 而不是 if。剪枝是 nums[i] 大于 0 时直接 break，因为后面不可能再凑出 0。\n```python\nnums.sort()\nfor i in range(len(nums) - 2):\n    if nums[i] > 0: break\n    if i > 0 and nums[i] == nums[i - 1]: continue\n    l, r = i + 1, len(nums) - 1\n    while l < r:\n        s = nums[i] + nums[l] + nums[r]\n        if s < 0: l += 1\n        elif s > 0: r -= 1\n        else:\n            res.append([nums[i], nums[l], nums[r]])\n            l += 1\n            while l < r and nums[l] == nums[l - 1]: l += 1\n```",
    points: ["排序后固定一个数加双指针夹逼", "讲清三处去重分别在哪", "剪枝：nums[i] 大于 0 直接退出"],
    follow: "如果是四数之和，怎么控制在 O(n³) 以内",
    sources: [{ repo: "leetcode-master", path: "problems/0015.三数之和.md" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-array-sliding-window",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 3,
    tags: ["滑动窗口", "哈希表", "字符串"],
    question: "最小覆盖子串：滑动窗口什么时候收缩左边界",
    answer: "窗口用 left 和 right 两个指针维护，right 每步右移把新字符纳入窗口，当窗口已经覆盖 t 的全部字符时，就尝试右移 left 缩小窗口并更新最优解。收缩的判据不是窗口长度，而是「窗口当前是否仍然合法」，先让窗口满足条件、再贪心地压缩它，这就是滑动窗口的骨架。\n- 时间 O(n + m)：left 和 right 各自单调右移，最多各走 n 步，合法性用计数表 O(1) 维护。\n- 空间 O(k)：k 为字符集大小，ASCII 场景下是常数。\n易错点：用 need 和 win 两张计数表加一个 valid 变量记录「已经满足数量要求的字符种类数」，否则每次比较整张表会退化；窗口长度按 right 减 left 加 1 计算，区间开闭约定要统一；t 中重复字符必须按次数满足，不能只判断出现过。\n```python\nneed, win = Counter(t), Counter()\nleft = valid = 0\nfor right, c in enumerate(s):\n    win[c] += 1\n    if win[c] == need[c]: valid += 1\n    while valid == len(need):\n        if right - left + 1 < best: best, res = right - left + 1, s[left:right + 1]\n        d = s[left]; left += 1\n        if win[d] == need[d]: valid -= 1\n        win[d] -= 1\n```",
    points: ["窗口双指针：right 扩张 left 收缩", "收缩条件是窗口仍覆盖 t", "用 valid 计数避免每次全表比较"],
    follow: "如果要返回所有长度最小的覆盖子串，代码要改哪里",
    sources: [{ repo: "fucking-algorithm", path: "高频面试系列/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-array-prefix-sum",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 2,
    tags: ["前缀和", "哈希表", "数组"],
    question: "和为 K 的子数组：前缀和配哈希表怎么用",
    answer: "子数组 nums[i..j] 的和等于 pre[j+1] 减 pre[i]，要求它等于 k，等价于 pre[i] 等于 pre[j+1] 减 k。于是边扫边把「出现过的前缀和到出现次数」记进哈希表，扫到 j 时查一次表就知道有多少个 i 满足条件。\n- 时间 O(n)：每个位置做一次哈希查询，均摊 O(1)。\n- 空间 O(n)：最坏情况所有前缀和互不相同。\n易错点：必须先把 0 以次数 1 放进表里，否则从下标 0 开始的子数组会漏掉；数组含负数时前缀和不再单调，不能用滑动窗口，这正是本题必须用哈希而不是双指针的原因。\n```python\ncnt = dict()\ncnt[0] = 1\ntotal = ans = 0\nfor x in nums:\n    total += x\n    ans += cnt.get(total - k, 0)\n    cnt[total] = cnt.get(total, 0) + 1\nreturn ans\n```",
    points: ["把子数组和转成两个前缀和之差", "哈希表记录前缀和出现次数", "初始化 0 出现一次"],
    follow: "如果数组元素全是正数，能不能用滑动窗口省下这张表",
    sources: [{ repo: "fucking-algorithm", path: "高频面试系列/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-linked-list-reverse",
    category: "algo",
    topic: "链表",
    difficulty: 1,
    tags: ["链表", "指针", "递归"],
    question: "反转链表：迭代和递归两种写法，各自的坑在哪",
    answer: "迭代用三个指针：pre 指向已经反转部分的头，cur 是当前节点。每轮先用 nxt 暂存 cur.next，再让 cur.next 指向 pre，最后 pre 和 cur 整体前移。暂存这一步是关键，不先存 next 链表就断了。\n- 时间 O(n)：每个节点只访问一次。\n- 空间：迭代 O(1)，只有常数个指针；递归时间同为 O(n)，但栈深度为 n，空间 O(n)，这是常被追问的对比点。\n易错点：返回的是 pre 而不是 cur，循环结束时 cur 已经是空；递归终止条件是 head 为空或 head.next 为空；回溯时用 head.next.next 指向 head 完成反转，并且一定要把 head.next 置空，否则尾部会成环。\n```python\npre, cur = None, head\nwhile cur:\n    nxt = cur.next\n    cur.next = pre\n    pre, cur = cur, nxt\nreturn pre\n```",
    points: ["三指针迭代，先暂存 next 再改指向", "说明递归栈空间是 O(n)", "返回 pre，递归尾部要置空"],
    follow: "如果只反转链表中区间 m 到 n 的节点，怎么处理",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-linked-list-cycle",
    category: "algo",
    topic: "链表",
    difficulty: 2,
    tags: ["链表", "快慢指针", "双指针"],
    question: "怎么判断链表有环，并找到环的入口节点",
    answer: "快指针每次走两步，慢指针每次走一步。有环时快指针先入环并不断逼近慢指针，两者必定相遇；无环时快指针先走到空。相遇后把一个指针放回头节点，两个指针都改成每次走一步，再次相遇的位置就是环的入口。\n- 时间 O(n)：慢指针入环前走 n 步，之后两者最多再走一圈环长。\n- 空间 O(1)：只用两个指针，不用哈希表存访问过的节点。\n为什么第二次相遇是入口：设头到入口距离为 a，入口到相遇点为 b，环长为 L。相遇时快指针比慢指针多走了整数倍环长，即 a 加 b 等于 k 倍 L，所以从相遇点再走 a 步正好回到入口。易错点：循环条件是快指针和快指针的 next 都非空，只判一个会空指针；用哈希表记录访问过的节点虽然简单，但空间是 O(n)。\n```python\nslow = fast = head\nwhile fast and fast.next:\n    slow, fast = slow.next, fast.next.next\n    if slow is fast:\n        slow = head\n        while slow is not fast:\n            slow, fast = slow.next, fast.next\n        return slow\nreturn None\n```",
    points: ["快慢指针相遇即证明有环", "相遇后一指针回头同步走找入口", "推导 a 加 b 与环长的关系"],
    follow: "如果链表可能有环，怎么在 O(1) 空间判断两个链表是否相交",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "数据结构/" }],
  },
  {
    id: "algo-linked-list-intersection",
    category: "algo",
    topic: "链表",
    difficulty: 1,
    tags: ["链表", "双指针", "指针"],
    question: "相交链表：怎么用 O(1) 空间找到第一个公共节点",
    answer: "两个指针分别从 headA 和 headB 出发，走到末尾就跳到另一条链表的头部继续走。设两条链表长度差为 d，先走完自己那条的指针会去走对方多出来的 d 步，于是两者在第二轮一定同时到达相交点，走的总步数都是两条链表长度之和。\n- 时间 O(m + n)：每个指针最多走两条链表的长度。\n- 空间 O(1)：只有两个指针，既不用哈希表也不用先求长度差。\n易错点：循环条件写成两个指针不相等，而不是比较它们的 next，否则会停在相交点的前一个；没有交点时两个指针会同时变成空，循环自然结束并返回空，不会死循环；两个指针在相交点之后共享同一段，所以长度差只出现在相交点之前。\n```python\np, q = headA, headB\nwhile p is not q:\n    p = p.next if p else headB\n    q = q.next if q else headA\nreturn p\n```",
    points: ["两指针走完自己接对方链表", "解释总步数相同必然相遇", "循环条件用两个指针不相等"],
    follow: "如果链表可能有环，这个换头走法还成立吗",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-linked-list-merge",
    category: "algo",
    topic: "链表",
    difficulty: 1,
    tags: ["链表", "递归", "指针"],
    question: "合并两个有序链表：递归写法为什么空间是 O(n)",
    answer: "每次比较两个头节点，把较小的那个摘下来接到结果尾部，再递归处理剩下的部分。递归函数的返回值是「合并后的头节点」，所以让较小节点的 next 指向递归结果即可。\n- 时间 O(m + n)：每个节点恰好被摘下来一次。\n- 空间：迭代写法 O(1)，递归写法 O(m + n)，因为每合并一个节点就压一层栈，最坏情况栈深等于总节点数，这是面试最爱追问的点。\n易错点：用哨兵节点可以省掉结果为空的特判，最后返回哨兵的 next；迭代时某一条走完，直接把另一条整体挂到尾部，不要再用 while 逐个搬；比较用小于等于，相等时取第一条，这样才保持稳定。\n```python\ndummy = cur = ListNode(0)\nwhile l1 and l2:\n    if l1.val <= l2.val: cur.next, l1 = l1, l1.next\n    else: cur.next, l2 = l2, l2.next\n    cur = cur.next\ncur.next = l1 or l2\nreturn dummy.next\n```",
    points: ["比较头节点，摘下较小的接到结果", "讲清递归空间是 O(n) 的原因", "哨兵节点加剩余部分整体挂载"],
    follow: "如果是合并 K 个升序链表，怎么做到 O(N log K)",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-binary-tree-level-order",
    category: "algo",
    topic: "二叉树",
    difficulty: 1,
    tags: ["二叉树", "BFS", "队列"],
    question: "二叉树层序遍历：怎么按层输出，为什么用队列",
    answer: "队列先进先出，保证第 i 层的节点一定在第 i 加 1 层之前全部出队。每轮循环先记下当前队列长度 size，然后只弹出 size 个节点，这一批正好是同一层，把它们的孩子依次入队就得到下一层。\n- 时间 O(n)：每个节点进出队各一次。\n- 空间 O(w)：w 是树的最大宽度，满二叉树最后一层约 n 的一半，所以最坏是 O(n)。\n易错点：必须用 size 固定本层节点数，直接写队列非空循环会把所有层混在一起；根节点为空要先返回空数组；用 DFS 带一个深度参数也能按层收集，但求最短路径、找每层最右节点这类问题用 BFS 更自然，因为 BFS 第一次到达就是最短层数。\n```python\nq, res = deque([root]), []\nwhile q:\n    level = []\n    for _ in range(len(q)):\n        node = q.popleft()\n        level.append(node.val)\n        if node.left: q.append(node.left)\n        if node.right: q.append(node.right)\n    res.append(level)\n```",
    points: ["队列保证按层顺序出队", "用 size 固定本层节点数", "空间是最大宽度 O(w)"],
    follow: "如果要求之字形层序遍历，改动最小的方法是什么",
    sources: [{ repo: "hello-algo", path: "docs/chapter_tree/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-binary-tree-bst-validate",
    category: "algo",
    topic: "二叉树",
    difficulty: 2,
    tags: ["BST", "中序遍历", "递归"],
    question: "验证二叉搜索树：为什么只比较父子节点是错的",
    answer: "BST 的定义是整棵左子树都小于根、整棵右子树都大于根，只比较某个节点和它的左右孩子会漏掉跨层违规，比如右子树里塞了一个比根小的值。两种正确做法：中序遍历检查序列严格递增；或者递归时携带上下界，进左子树把上界收紧为当前值，进右子树把下界收紧为当前值。\n- 时间 O(n)：每个节点访问一次。\n- 空间 O(h)：h 是树高，即递归栈深度；中序迭代法显式用栈也是 O(h)，退化成链时是 O(n)。\n易错点：边界必须用严格不等号，等值节点不满足 BST；上下界要用哨兵值或空表示无穷，避免节点值正好落在 int 边界时误判；中序遍历只需保存前一个节点，不必存整条序列。\n```python\ndef check(node, low, high):\n    if not node: return True\n    if node.val <= low or node.val >= high: return False\n    return check(node.left, low, node.val) and check(node.right, node.val, high)\n```",
    points: ["BST 约束的是整棵子树而非父子", "中序递增或递归传上下界", "等值非法，边界要用严格不等号"],
    follow: "在 BST 中删除一个节点，需要分哪几种情况",
    sources: [{ repo: "hello-algo", path: "docs/chapter_tree/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-binary-tree-lca",
    category: "algo",
    topic: "二叉树",
    difficulty: 2,
    tags: ["二叉树", "递归", "LCA"],
    question: "二叉树的最近公共祖先：递归为什么一次遍历就够",
    answer: "递归函数的语义是「以当前节点为根的子树里，是否找到了 p 或 q，找到就返回那个节点」。如果左右子树都返回了非空，说明 p 和 q 分居两侧，当前节点就是最近公共祖先；如果只有一侧非空，就把这一侧的结果继续往上传递。\n- 时间 O(n)：最坏要遍历所有节点。\n- 空间 O(h)：递归栈深度，树退化成链时是 O(n)。\n易错点：当前节点等于 p 或 q 时直接返回自己，这是递归终止条件的一部分，也保证了「自己是自己的祖先」这种输入正确；某一侧返回非空不代表已经找到答案，必须看左右是否同时非空；如果树是 BST，可以利用大小关系把两个节点分到两侧，复杂度降到 O(h)。\n```python\ndef lca(root, p, q):\n    if not root or root is p or root is q: return root\n    l = lca(root.left, p, q)\n    r = lca(root.right, p, q)\n    if l and r: return root\n    return l or r\n```",
    points: ["递归返回子树里是否含 p 或 q", "左右都非空则当前节点即答案", "空间复杂度是树高 O(h)"],
    follow: "如果这棵树是 BST，能不能不遍历整棵树就找到 LCA",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-binary-tree-serialize",
    category: "algo",
    topic: "二叉树",
    difficulty: 3,
    tags: ["二叉树", "序列化", "DFS"],
    question: "二叉树的序列化与反序列化：为什么必须补空节点",
    answer: "只存非空节点的先序序列无法唯一还原二叉树，因为每个节点缺失的孩子位置无从判断，不同的树可能得到同一个序列。补上空节点占位符后，每个节点的两个子位置都有记录，先序加空标记就能唯一确定结构。反序列化按同样的顺序消费 token，遇到空标记就返回空。\n- 时间 O(n)：序列化和反序列化各遍历一次。\n- 空间 O(n)：结果字符串是 O(n)，链状树时递归栈也是 O(n)。\n易错点：分隔符要选不会出现在节点值里的字符，空标记也不能和真实值混淆；层序 BFS 写法同样要补空节点，反序列化时用下标遍历比弹出队首更省；递归反序列化必须严格按先序顺序消费，先建左子树再建右子树，顺序错了整棵树就错位。\n```python\ndef ser(node):\n    if not node: return 'X'\n    return str(node.val) + ',' + ser(node.left) + ',' + ser(node.right)\n\ndef de(tokens):\n    v = next(tokens)\n    if v == 'X': return None\n    node = TreeNode(int(v))\n    node.left, node.right = de(tokens), de(tokens)\n    return node\n```",
    points: ["空节点必须占位才能唯一还原", "先序加空标记，反序列化同序消费", "复杂度 O(n)，注意分隔符选择"],
    follow: "如果要求序列化结果尽量短，你会怎么压缩",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_tree/" }],
  },
  {
    id: "algo-dp-knapsack",
    category: "algo",
    topic: "动态规划",
    difficulty: 2,
    tags: ["动态规划", "背包", "状态压缩"],
    question: "0-1 背包和完全背包：一维数组的遍历方向为什么相反",
    answer: "一维数组里 dp[j] 表示容量为 j 时的最大价值。0-1 背包内层容量必须从大到小遍历，因为 dp[j] 依赖的是上一轮的 dp[j 减 w]，倒序保证那个位置还没被本轮更新过；完全背包允许重复选，正序让 dp[j 减 w] 已经是本轮的新值，正好实现「再选一次」。\n- 时间 O(n 乘 V)：物品数乘容量，两种背包一样。\n- 空间 O(V)：一维滚动数组把二维的 O(n 乘 V) 压掉了。\n易错点：遍历方向写反是最常见的错误，结果会悄悄变成另一种背包；二维写法里 0-1 背包的容量也必须倒序；求组合数时先遍历物品再遍历容量，求排列数才反过来，顺序不同答案含义完全不同。\n```python\nfor w, v in items:\n    for j in range(cap, w - 1, -1):\n        dp[j] = max(dp[j], dp[j - w] + v)\n```",
    points: ["一维 dp 表示容量 j 的最优值", "倒序保证用到上一轮状态", "正序对应完全背包可重复选"],
    follow: "如果要求恰好装满背包，初始化要怎么改",
    sources: [{ repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }, { repo: "fucking-algorithm", path: "动态规划/" }],
  },
  {
    id: "algo-dp-lis",
    category: "algo",
    topic: "动态规划",
    difficulty: 2,
    tags: ["动态规划", "二分查找", "LIS"],
    question: "最长递增子序列：O(n log n) 的解法在维护什么",
    answer: "维护一个数组 tails，tails[i] 表示所有长度为 i 加 1 的递增子序列中，结尾最小的那个值。这个数组一定是严格递增的，所以可以二分找到第一个不小于 x 的位置并替换它。替换而不是追加，是为了给后面的元素留出更大的接续空间，让子序列更容易变长。\n- 时间 O(n log n)：每个元素一次二分。\n- 空间 O(n)：tails 长度最多等于答案长度。\n注意 tails 不是真正的 LIS，它只是「长度为 i 加 1 时的最小结尾」，所以这个做法只能求长度，不能还原序列。要还原序列得用 O(n 方) 的 dp 加前驱数组，或者额外记录每个元素入表时的前驱下标。易错点：二分要用找第一个不小于 x 的位置，用找第一个大于 x 的位置会变成非严格递增。\n```python\nimport bisect\ntails = []\nfor x in nums:\n    i = bisect.bisect_left(tails, x)\n    if i == len(tails): tails.append(x)\n    else: tails[i] = x\nreturn len(tails)\n```",
    points: ["tails 存长度为 i 加 1 的最小结尾", "二分找第一个不小于 x 的位置替换", "说明 tails 不是真正的 LIS"],
    follow: "如果要输出任意一条最长递增子序列，怎么改",
    sources: [{ repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-dp-edit-distance",
    category: "algo",
    topic: "动态规划",
    difficulty: 3,
    tags: ["动态规划", "字符串", "编辑距离"],
    question: "编辑距离：状态怎么定义，三种操作对应哪个转移",
    answer: "dp[i][j] 表示 word1 的前 i 个字符转成 word2 的前 j 个字符所需的最少操作数。若末尾字符相同，直接继承 dp[i-1][j-1]；否则取三种操作的最小值加一：删除对应 dp[i-1][j]，插入对应 dp[i][j-1]，替换对应 dp[i-1][j-1]。\n- 时间 O(m 乘 n)：两层循环填表。\n- 空间 O(m 乘 n)，用滚动数组可以降到 O(min(m, n))。\n易错点：初始化必须单独处理，dp[i][0] 等于 i、dp[0][j] 等于 j，代表全删或全插；状态定义用「前 i 个字符」而不是「第 i 个字符」，可以省掉大量边界判断；操作名字和转移的对应关系容易记混，按「保留谁的前缀」去理解更稳；只允许删除和插入时答案就是两串长度之和减去两倍最长公共子序列长度。\n```python\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if a[i - 1] == b[j - 1]: dp[i][j] = dp[i - 1][j - 1]\n        else: dp[i][j] = 1 + min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1])\n```",
    points: ["dp 定义为前 i 与前 j 个字符", "相同则继承，不同则三选一加一", "初始化首行首列为 i 和 j"],
    follow: "如果只允许删除和插入，答案会变成什么",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }],
  },
  {
    id: "algo-dp-state-design",
    category: "algo",
    topic: "动态规划",
    difficulty: 2,
    tags: ["动态规划", "状态定义", "方法论"],
    question: "怎么判断一道题能不能用动态规划，状态该怎么定义",
    answer: "先看两个条件：最优子结构，即大问题的最优解能由子问题的最优解拼出来；无后效性，即状态一旦确定，后面的决策不受前面怎么走来的影响。再看有没有重叠子问题，有才值得用 DP，否则递归或贪心就够了。\n状态定义是最关键的一步，做法是把「决策过程」翻译成变量。以打家劫舍为例，把 dp[i] 定义为「考虑前 i 间房能偷到的最大金额」，转移就是偷与不偷取较大者；如果含义定成「第 i 间必须偷」，转移就要多带一个维度，边界也更难写。\n- 时间通常是状态数乘单次转移代价：打家劫舍是 O(n)，背包是 O(n 乘 V)。\n- 空间等于状态数，能用滚动数组时只保留上一层。\n易错点：状态含义写不清楚就一定会错，建议先用一句话把 dp[i] 念出来，念不通就说明定义有问题；边界和初始化要单独推，比如打家劫舍的 dp[0] 和 dp[1]；遍历顺序必须保证用到的状态已经算好。\n```python\ndp = [0] * (n + 2)\nfor i, x in enumerate(nums):\n    dp[i + 2] = max(dp[i + 1], dp[i] + x)\nreturn dp[n + 1]\n```",
    points: ["最优子结构加无后效性加重叠子问题", "用一句话说清 dp[i] 的含义", "状态数乘转移代价即复杂度"],
    follow: "如果状态定义改成第 i 间必须偷，转移方程怎么变",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }],
  },
  {
    id: "algo-backtracking-permutation",
    category: "algo",
    topic: "回溯",
    difficulty: 2,
    tags: ["回溯", "递归", "去重"],
    question: "全排列 II：撤销选择怎么写，重复元素怎么去重",
    answer: "回溯的骨架是「做选择、递归、撤销选择」，撤销必须和选择严格对称，否则路径会被污染。含重复元素时先排序让相同的数相邻，再用 used 数组加一条剪枝：当当前值和前一个值相等、且前一个值还没被使用时，跳过当前分支。它的含义是「同一层里相同的值只由第一个上场的那个负责」，这样就不会产生重复排列。\n- 时间 O(n 乘 n!)：共 n! 个叶子，每个叶子复制路径要 O(n)。\n- 空间 O(n)：递归栈、used 数组和当前路径。\n易错点：剪枝条件里的「前一个未被使用」必须成立才跳过，写成已被使用就变成另一种错误的去重；子集和组合问题靠 start 参数保证只往后选来避免顺序重复，排列问题才需要 used 数组；结果要拷贝一份再收集，否则存的是同一个引用。\n```python\ndef dfs(path):\n    if len(path) == len(nums):\n        res.append(path[:]); return\n    for i in range(len(nums)):\n        if used[i]: continue\n        if i > 0 and nums[i] == nums[i - 1] and not used[i - 1]: continue\n        used[i] = True; path.append(nums[i])\n        dfs(path)\n        path.pop(); used[i] = False\n```",
    points: ["做选择与撤销选择严格对称", "排序加 used 数组剪枝去重", "剪枝要求前一个元素未被使用"],
    follow: "如果要求按字典序输出全部排列，需要额外做什么",
    sources: [{ repo: "hello-algo", path: "docs/chapter_backtracking/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-backtracking-combination-sum",
    category: "algo",
    topic: "回溯",
    difficulty: 2,
    tags: ["回溯", "剪枝", "组合"],
    question: "组合总和：元素可重复选取时，为什么递归传 i 而不是 i 加 1",
    answer: "传 i 表示下一层还能再选当前元素，传 i 加 1 表示当前元素在后续分支里被排除。组合问题用 start 参数控制「只能往后选」，天然避免同一组数因为顺序不同被重复收集；允许重复选取，就把下一层的起点留在原地。\n- 时间上界是指数级：准确说是 O(n 的 target 次方)，实际被剪枝大幅削减。\n- 空间 O(target 除以最小元素)：递归深度受目标和与最小元素限制。\n易错点：先排序，当剩余目标小于当前元素时直接 break，能剪掉整层而不是只跳过一个；用「剩余目标」往下传比用累加和更省参数；找到一组解后要立刻 return，不要再往深处走；同一层跳过重复值可以再省一批分支。\n```python\ndef dfs(start, rest, path):\n    if rest == 0:\n        res.append(path[:]); return\n    for i in range(start, len(nums)):\n        if nums[i] > rest: break\n        path.append(nums[i])\n        dfs(i, rest - nums[i], path)\n        path.pop()\n```",
    points: ["start 参数避免组合顺序重复", "传 i 允许重复选，传 i 加 1 不允许", "排序后剩余不足即 break 剪枝"],
    follow: "如果每个数字只能使用一次，代码要改哪两处",
    sources: [{ repo: "hello-algo", path: "docs/chapter_backtracking/" }, { repo: "fucking-algorithm", path: "算法思维/" }],
  },
  {
    id: "algo-backtracking-n-queens",
    category: "algo",
    topic: "回溯",
    difficulty: 3,
    tags: ["回溯", "剪枝", "N皇后"],
    question: "N 皇后：怎么在 O(1) 时间判断一列和两条对角线是否冲突",
    answer: "逐行放置皇后，每行只放一个，天然避免了行冲突。用三个集合记录已被占用的列、主对角线和副对角线：同一主对角线上行号减列号相等，同一副对角线上行号加列号相等，于是冲突判断变成三次哈希查询。\n- 时间 O(n!)：第一行 n 种选择，之后逐行减少，实际远小于这个上界。\n- 空间 O(n)：三个集合加递归栈深度 n。\n易错点：行号减列号可能为负，用数组代替集合时要加偏移量 n；放置和撤销三个集合必须严格对称；只求方案数时不需要保存棋盘，能显著降低常数；剪枝的本质是尽早发现某一行已经没有合法位置，判断越早整体越快。\n```python\ndef dfs(row):\n    if row == n:\n        res.append(1); return\n    for col in range(n):\n        if col in cols or row - col in d1 or row + col in d2: continue\n        cols.add(col); d1.add(row - col); d2.add(row + col)\n        dfs(row + 1)\n        cols.discard(col); d1.discard(row - col); d2.discard(row + col)\n```",
    points: ["逐行放置，天然避免行冲突", "用行加减列判断两条对角线", "选择与撤销严格对称"],
    follow: "如果只要求方案数，能怎么优化常数",
    sources: [{ repo: "hello-algo", path: "docs/chapter_backtracking/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-greedy-jump-game",
    category: "algo",
    topic: "贪心",
    difficulty: 2,
    tags: ["贪心", "数组", "区间"],
    question: "跳跃游戏：为什么维护最远可达位置就能判断能否到终点",
    answer: "从左往右扫，维护当前能到达的最远下标 reach。只要 i 不超过 reach，就说明第 i 格可达，于是可以用 i 加 nums[i] 去更新 reach。扫描过程中一旦 reach 覆盖了最后一个下标，就可以立刻返回成功。\n- 时间 O(n)：一次遍历，每个位置只算一次。\n- 空间 O(1)：只用一个变量。\n贪心为什么成立：可达性具有单调性，能到达更远的位置就一定覆盖了中间所有位置，所以「最远可达」这个信息足以代表整个可达集合，不需要记录具体走法。易错点：循环里要先判断 i 超过 reach 就返回失败，否则会走到不可达的格子上；求的是可行性，如果问最少步数要用另一套贪心，每次在当前可达区间内选能跳最远的那个，再统一更新边界。\n```python\nreach = 0\nfor i, step in enumerate(nums):\n    if i > reach: return False\n    reach = max(reach, i + step)\n    if reach >= len(nums) - 1: return True\n```",
    points: ["维护最远可达下标 reach", "解释可达性单调所以贪心成立", "i 超过 reach 立即失败"],
    follow: "如果要求最少跳跃次数，贪心策略怎么改",
    sources: [{ repo: "hello-algo", path: "docs/chapter_greedy/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-greedy-interval",
    category: "algo",
    topic: "贪心",
    difficulty: 2,
    tags: ["贪心", "区间", "排序"],
    question: "无重叠区间：为什么按右端点排序而不是左端点",
    answer: "要让保留的区间尽量多，直觉是「越早结束的区间越不占地方」。按右端点升序排序后，每次选择结束最早且不与上一个已选区间重叠的区间，就是最优解。按左端点排序时，一个开始很早但跨度极大的区间会挡住后面一堆区间，贪心选择不再最优。\n- 时间 O(n log n)：排序主导，之后一次线性扫描。\n- 空间 O(1)：不计排序本身的栈开销。\n正确性可以用交换论证：最优解的第一个区间总能换成右端点最小的那个而不变差，反复替换就得到贪心解。易错点：判断重叠用下一个区间的左端点是否小于上一个的右端点，闭区间相等也算重叠；题目问「需要移除的区间数」时等于总数减去保留数，别重复统计。\n```python\nintervals.sort(key=lambda x: x[1])\ncount, end = 0, float('-inf')\nfor l, r in intervals:\n    if l >= end:\n        count += 1; end = r\nreturn len(intervals) - count\n```",
    points: ["按右端点升序排序", "每次选结束最早且不重叠的区间", "用交换论证说明贪心最优"],
    follow: "如果是区间合并和会议室安排，排序键分别是什么",
    sources: [{ repo: "hello-algo", path: "docs/chapter_greedy/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-sorting-quicksort",
    category: "algo",
    topic: "排序",
    difficulty: 2,
    tags: ["排序", "快速排序", "分治"],
    question: "手写快速排序，说明它的最坏情况与优化",
    answer: "选一个基准，把数组分成小于基准和大于基准两部分，再对两部分递归。核心是划分：用双指针从两端向中间走，左边找不小于基准的、右边找不大于基准的，交换后继续，最后把基准放到分界点。\n- 平均时间 O(n log n)：每层划分 O(n)，共约 log n 层。\n- 最坏时间 O(n 方)：数组已经有序且每次取首元素作基准时，划分极不平衡；递归栈最坏 O(n)，平均 O(log n)。\n- 空间 O(log n)：只用了递归栈，是原地排序。\n优化有三个方向：随机选基准或三数取中，避免有序输入退化；小区间改用插入排序；把与基准相等的元素集中到中间（三路划分），处理大量重复元素时能从 O(n 方) 降到 O(n)。另外快排不稳定，需要稳定就选归并。\n```python\ndef qs(a, lo, hi):\n    if lo >= hi: return\n    p, i = a[hi], lo\n    for j in range(lo, hi):\n        if a[j] < p:\n            a[i], a[j] = a[j], a[i]; i += 1\n    a[i], a[hi] = a[hi], a[i]\n    qs(a, lo, i - 1); qs(a, i + 1, hi)\n```",
    points: ["讲清划分的双指针过程", "最坏 O(n 方) 的触发条件", "随机基准与三路划分优化"],
    follow: "如果数组里有大量重复元素，快排怎么避免退化",
    sources: [{ repo: "hello-algo", path: "docs/chapter_sorting/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-sorting-mergesort",
    category: "algo",
    topic: "排序",
    difficulty: 1,
    tags: ["排序", "归并排序", "稳定性"],
    question: "归并排序的思路，为什么它稳定、空间为什么是 O(n)",
    answer: "把数组从中间切开，分别排好两半，再把两个有序数组合并成一个：每次比较两段的头部，取较小者放进临时数组，某一段用完就把另一段整体接上。\n- 时间 O(n log n)：递归深度 log n，每层合并总共 O(n)，最好、最坏、平均都一样，这是它相对快排的最大优势。\n- 空间 O(n)：合并需要和原数组等长的临时数组。\n稳定性来自合并时的判断：相等时优先取左半段的元素，所以相等元素的相对次序不会被改变。这一点在按多字段排序（先按分数、再按姓名）时很关键。归并还特别适合链表：链表合并不需要额外数组，空间降到 O(log n)，只有递归栈。易错点：临时数组要拷回原数组，否则外层看不到排序结果。\n```python\ndef ms(a):\n    if len(a) <= 1: return a\n    mid = len(a) // 2\n    l, r = ms(a[:mid]), ms(a[mid:])\n    return merge(l, r)\n```",
    points: ["分治加合并两个有序数组", "稳定来自相等时先取左边", "O(n) 额外空间，链表场景更优"],
    follow: "如果要求 O(1) 额外空间的稳定排序，有哪些选择",
    sources: [{ repo: "hello-algo", path: "docs/chapter_sorting/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-sorting-topk-heap",
    category: "algo",
    topic: "排序",
    difficulty: 3,
    tags: ["排序", "堆", "TopK"],
    question: "求第 K 大的元素：小顶堆和快速选择分别怎么用",
    answer: "小顶堆做法：维护一个大小为 K 的小顶堆，遍历数组，堆没满就压入，满了就比较堆顶，比堆顶大就替换。遍历结束后堆顶就是第 K 大，因为堆里始终保留着当前最大的 K 个元素。\n- 堆做法时间 O(n log K)，空间 O(K)：适合 n 极大、数据流式到达、内存放不下的场景。\n- 快速选择平均 O(n)，最坏 O(n 方)：用划分缩小范围，每次只递归一边，空间 O(1)。理论更快，但需要能随机访问全部数据。\n易错点：第 K 大用小顶堆、第 K 小用大顶堆，方向搞反是最常见的错误；快速选择的最坏情况要靠随机基准规避；求前 K 个高频元素时比较的是频率而不是数值，堆里存的应该是元素和频率的组合。\n```python\nimport heapq\nh = []\nfor x in nums:\n    if len(h) < k: heapq.heappush(h, x)\n    elif x > h[0]: heapq.heapreplace(h, x)\nreturn h[0]\n```",
    points: ["小顶堆保留最大的 K 个，堆顶即答案", "对比 O(n log K) 与平均 O(n)", "数据流场景优先选堆"],
    follow: "如果数据有 100 亿条而内存只有 1G，怎么求 Top K",
    sources: [{ repo: "hello-algo", path: "docs/chapter_heap/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-binary-search-boundary",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 1,
    tags: ["二分查找", "边界", "循环不变量"],
    question: "写一个二分查找，怎么避免死循环和下标越界",
    answer: "先确定区间定义：用左闭右闭区间时，循环条件是左指针不超过右指针，更新成左指针取 mid 加 1 或右指针取 mid 减 1；用左闭右开区间时，循环条件是左指针小于右指针，右指针取 mid。区间定义和更新方式必须配套，混用就会死循环或漏查。\n- 时间 O(log n)：每次把搜索区间砍掉一半。\n- 空间 O(1)：迭代写法只有常数个变量。\n易错点：mid 写成两数相加除以二，在极端大数下会溢出，要写成左指针加区间长度的一半；只在「找第一个满足条件的位置」这类变体里才写右指针取 mid，普通查找这么写会卡死；循环结束后还要判断左指针是否越界，因为目标值可能根本不存在。\n```python\nlo, hi = 0, len(a) - 1\nwhile lo <= hi:\n    mid = lo + (hi - lo) // 2\n    if a[mid] == target: return mid\n    if a[mid] < target: lo = mid + 1\n    else: hi = mid - 1\nreturn -1\n```",
    points: ["先定区间开闭，再配循环条件", "mid 用左指针加区间一半防溢出", "右指针取 mid 只用于找边界变体"],
    follow: "如果要找目标值第一次和最后一次出现的位置呢",
    sources: [{ repo: "hello-algo", path: "docs/chapter_searching/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-binary-search-rotated",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 2,
    tags: ["二分查找", "旋转数组", "数组"],
    question: "搜索旋转排序数组：怎么在 O(log n) 内判断往哪半边找",
    answer: "旋转后的数组一定有一半是有序的。取到 mid 后先判断哪一半有序：如果左端点的值不大于 mid 的值，说明左半段有序，再看目标是否落在左端点与 mid 之间，是就往左找，否则往右；否则右半段有序，同理判断。\n- 时间 O(log n)：每轮仍然砍掉一半。\n- 空间 O(1)：只用左右指针和 mid。\n关键在于用「有序的那一半」当判据，而不是直接比较 mid 和目标值。易错点：判断有序时要用小于等于而不是小于，因为区间只剩一个元素时左右端点与 mid 重合，也必须算作有序；数组含重复元素时（比如一和一和一和零和一）无法判断哪半有序，只能退化成 O(n)，做法是遇到左右端点相等就收缩一步再继续二分。\n```python\nwhile lo <= hi:\n    mid = lo + (hi - lo) // 2\n    if a[mid] == t: return mid\n    if a[lo] <= a[mid]:\n        if a[lo] <= t < a[mid]: hi = mid - 1\n        else: lo = mid + 1\n    else:\n        if a[mid] < t <= a[hi]: lo = mid + 1\n        else: hi = mid - 1\n```",
    points: ["旋转后必有一半是有序的", "用有序那半判断目标是否在区间内", "含重复元素时退化成 O(n)"],
    follow: "如果数组在旋转前就允许有重复元素，怎么处理",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_searching/" }],
  },
  {
    id: "algo-binary-search-answer",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 3,
    tags: ["二分查找", "二分答案", "单调性"],
    question: "二分答案：怎么判断一道题可以把答案本身当二分对象",
    answer: "当「答案是一个数」且「可行性随答案单调变化」时，就可以二分答案：猜一个值 x，写一个 check 函数判断 x 是否可行，再按可行性收缩区间。典型题如爱吃香蕉的珂珂（速度越大耗时越少）、分割数组的最大值（容量越大需要的段数越少）。\n- 时间 O(n log V)：每次 check 是 O(n)，二分次数是答案值域的对数。\n- 空间 O(1)：只用常数个变量。\n三个要点：确定答案的上下界，下界常取 1 或单个最大值，上界取总和或最大值的某个倍数；check 函数必须写对，它决定整个算法的正确性；想清楚要找「最小的可行值」还是「最大的可行值」，这决定返回左指针还是右指针。易错点：单调方向搞反会得到完全相反的结果，写完最好手动验证两个端点。\n```python\nlo, hi = 1, max(piles)\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if can_finish(mid): hi = mid\n    else: lo = mid + 1\nreturn lo\n```",
    points: ["答案单调则把最优问题转成判定", "写对 check 并确定上下界", "区分求最小可行还是最大可行"],
    follow: "如果每次 check 的代价是 O(n)，还有更快的做法吗",
    sources: [{ repo: "hello-algo", path: "docs/chapter_searching/" }, { repo: "fucking-algorithm", path: "算法思维/" }],
  },
  {
    id: "algo-stack-queue-min-stack",
    category: "algo",
    topic: "栈与队列",
    difficulty: 1,
    tags: ["栈", "设计", "辅助栈"],
    question: "最小栈：怎么在 O(1) 时间取到栈里的最小值",
    answer: "不能只用一个变量记最小值：一旦最小值被弹出，就没法知道第二小的是谁。做法是再开一个辅助栈，每次入栈时把「当前最小值」也压进去，两个栈同进同出，辅助栈的栈顶就是当前最小值。\n- 时间 O(1)：入栈、出栈、取栈顶、取最小值都是常数操作。\n- 空间 O(n)：辅助栈和主栈等长；可以优化成只在新值不大于当前最小值时才压入，常见情况下空间更省。\n易错点：出栈时两个栈必须一起弹，只弹主栈会让最小值错位；辅助栈为空时入栈要直接压入新值；判空逻辑要和主栈保持一致；如果允许每次遍历找最小值，那就不是 O(1)，面试官会直接否掉。\n```python\ndef push(self, x):\n    self.data.append(x)\n    self.mins.append(x if not self.mins else min(x, self.mins[-1]))\n\ndef pop(self):\n    self.mins.pop()\n    return self.data.pop()\n```",
    points: ["辅助栈同步记录当前最小值", "四个操作都保持 O(1)", "出栈时两个栈必须一起弹"],
    follow: "如果要求辅助栈占用尽量小，怎么优化",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_stack_and_queue/" }],
  },
  {
    id: "algo-stack-queue-monotonic",
    category: "algo",
    topic: "栈与队列",
    difficulty: 2,
    tags: ["单调栈", "栈", "数组"],
    question: "单调栈：每日温度这类题为什么能一遍扫描出结果",
    answer: "维护一个从栈底到栈顶单调递减的下标栈。遍历到第 i 天时，只要栈顶那天的温度比今天低，就说明栈顶那天「第一次遇到更暖的日子」就是今天，于是弹出并结算答案；处理完再把 i 压栈。每个下标最多进栈一次、出栈一次。\n- 时间 O(n)：虽然有内层 while，但总弹出次数不超过 n，整体是均摊 O(1)。\n- 空间 O(n)：栈最多存下所有下标。\n单调栈的本质是「用一个栈记录还没找到答案的元素」，栈的单调性保证被弹出的那一刻就是它要的答案。易错点：栈里存下标而不是值，否则算不出天数差；比较符号决定找的是下一个更大还是下一个更小；求柱状图最大矩形、接雨水时，弹出后还要用新的栈顶当左边界，别忘了栈空时的处理。\n```python\nres, st = [0] * len(t), []\nfor i, x in enumerate(t):\n    while st and t[st[-1]] < x:\n        j = st.pop(); res[j] = i - j\n    st.append(i)\nreturn res\n```",
    points: ["栈里存下标且保持单调", "弹出时结算第一次更大的位置", "总弹出次数不超过 n 即均摊 O(n)"],
    follow: "如果数组是循环的，下一个更大元素怎么找",
    sources: [{ repo: "hello-algo", path: "docs/chapter_stack_and_queue/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-stack-queue-lru",
    category: "algo",
    topic: "栈与队列",
    difficulty: 2,
    tags: ["LRU", "哈希表", "双向链表"],
    question: "手写 LRU 缓存：为什么哈希表要配双向链表",
    answer: "LRU 需要两个能力：O(1) 查到某个 key，以及 O(1) 把任意节点移动到「最近使用」的位置并淘汰最久未使用的节点。哈希表负责前者，双向链表负责后者，因为双向链表删除任意节点只要改前后指针，单向链表做不到。节点里要同时存 key 和 value，淘汰时才能顺带从哈希表里删掉对应的 key。\n- 时间 O(1)：get 和 put 都是查表加常数次指针操作。\n- 空间 O(capacity)：哈希表和链表各存一份引用，节点数不超过容量。\n易错点：用哨兵头尾节点能省掉大量空链表特判；put 已存在的 key 要更新值并移到头部，不能只更新值；容量满时淘汰尾节点的前一个，同时删除哈希表里的条目；约定越靠头部越新，读写都要走同一个移动逻辑。\n```python\ndef get(self, key):\n    if key not in self.map: return -1\n    node = self.map[key]; self.move_to_head(node)\n    return node.val\n\ndef put(self, key, val):\n    if key in self.map:\n        self.map[key].val = val; self.move_to_head(self.map[key])\n    else:\n        if len(self.map) == self.cap: self.remove_tail()\n        self.add_head(Node(key, val))\n```",
    points: ["哈希表管查找，双向链表管顺序", "节点要同时存 key 和 value", "get 和 put 都保持 O(1)"],
    follow: "如果要求实现 LFU，结构上要增加什么",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "数据结构/" }],
  },
  {
    id: "algo-graph-islands",
    category: "algo",
    topic: "图论",
    difficulty: 2,
    tags: ["图论", "DFS", "BFS"],
    question: "岛屿数量：DFS 和 BFS 分别怎么写，最短路为什么必须用 BFS",
    answer: "遍历网格，遇到陆地就把答案加一，然后用 DFS 或 BFS 把与它相连的整片陆地标记成已访问，避免重复计数。DFS 靠递归一条路走到底，BFS 靠队列一圈圈向外扩散。\n- 时间 O(m 乘 n)：每个格子最多被访问一次。\n- 空间 O(m 乘 n)：DFS 最坏递归深度等于格子数，网格很大时可能爆栈，这时改用 BFS 或显式栈更稳。\nBFS 按层扩散，第一次到达某点时经过的层数就是最短距离；DFS 不保证第一次到达就是最短，所以无权图最短路、迷宫最少步数这类问题要用 BFS。易错点：标记已访问要放在入队时而不是出队时，否则同一格会被重复入队导致膨胀；网格 DFS 在大数据量下要考虑改成栈或并查集；岛屿数量也可以把二维坐标映射成一维，用并查集统计连通块个数。\n```python\ndef dfs(i, j):\n    if not (0 <= i < m and 0 <= j < n) or g[i][j] != '1': return\n    g[i][j] = '0'\n    for di, dj in DIRS: dfs(i + di, j + dj)\n```",
    points: ["遇到陆地计数并整片标记", "DFS 递归深度可能爆栈", "BFS 按层扩散所以能求最短路"],
    follow: "如果网格特别大，怎么避免递归爆栈",
    sources: [{ repo: "hello-algo", path: "docs/chapter_graph/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-graph-topological-sort",
    category: "algo",
    topic: "图论",
    difficulty: 3,
    tags: ["拓扑排序", "图论", "入度"],
    question: "课程表：拓扑排序怎么判环，Kahn 和 DFS 两种写法怎么选",
    answer: "Kahn 算法维护入度表，先把所有入度为 0 的节点入队，每次出队一个就把它指向的节点入度减一，减到 0 再入队。如果最终出队节点数小于总数，说明剩下的节点互相成环，无法完成全部课程。\n- 时间 O(V + E)：每个点和每条边各处理一次。\n- 空间 O(V + E)：入度数组、队列和邻接表。\nDFS 写法是后序遍历：节点递归返回时加入结果头部；如果递归中遇到「正在访问」的节点就说明有环，需要三色标记区分未访问、访问中和已完成。Kahn 更适合顺便求字典序最小的拓扑序，把队列换成优先队列即可；DFS 写法更短但判环要额外状态。易错点：建图时注意边的方向，先修课程指向后续课程；环的判定条件是结果长度不等于节点数。\n```python\nq = deque([i for i in range(n) if indeg[i] == 0])\norder = []\nwhile q:\n    u = q.popleft(); order.append(u)\n    for v in graph[u]:\n        indeg[v] -= 1\n        if indeg[v] == 0: q.append(v)\nreturn len(order) == n\n```",
    points: ["入度为 0 入队，逐层剥离", "出队数小于总数说明有环", "Kahn 与 DFS 三色标记的取舍"],
    follow: "如果要求输出字典序最小的课程顺序，怎么改",
    sources: [{ repo: "hello-algo", path: "docs/chapter_graph/" }, { repo: "fucking-algorithm", path: "数据结构/" }],
  },
  {
    id: "algo-complexity-amortized",
    category: "algo",
    topic: "复杂度分析",
    difficulty: 2,
    tags: ["复杂度", "均摊分析", "动态数组"],
    question: "均摊复杂度是什么，用两个栈实现队列和动态数组扩容举例",
    answer: "均摊复杂度是把一次昂贵操作的代价平摊到它前后的一批廉价操作上，衡量的是「一串操作的平均代价」，而不是单次最坏代价。所以「最坏 O(n) 加均摊 O(1)」并不矛盾。\n两个经典例子。一是用两个栈实现队列：入队直接压入 in 栈；出队时如果 out 栈为空，就把 in 栈全部倒过去再弹出。每个元素最多被搬运一次，n 次操作总代价 O(n)，所以出队均摊 O(1)，但某一次出队最坏是 O(n)。\n```python\ndef pop(self):\n    if not self.out:\n        while self.inn:\n            self.out.append(self.inn.pop())\n    return self.out.pop()\n```\n二是动态数组按倍数扩容：插入 n 个元素的总搬运次数是 1 加 2 加 4 一直加到不超过 n，总量不超过 2n，所以追加均摊 O(1)，但触发扩容那一次是 O(n)。\n易错点：均摊分析针对的是操作序列，不能对单次操作承诺 O(1)；扩容倍数选 1.5 或 2 决定均摊常数，如果每次只扩容固定大小，总代价会退化成 O(n 方)。",
    points: ["均摊是操作序列的平均而非单次", "两栈队列每个元素最多搬一次", "扩容总搬运量不超过 2n"],
    follow: "如果动态数组每次只扩容固定大小，总代价会变成多少",
    sources: [{ repo: "hello-algo", path: "docs/chapter_computational_complexity/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-complexity-master-theorem",
    category: "algo",
    topic: "复杂度分析",
    difficulty: 3,
    tags: ["复杂度", "主定理", "分治"],
    question: "主定理怎么用，归并排序和二分查找的复杂度怎么推出来",
    answer: "分治算法的时间可以写成 T(n) 等于 a 乘 T(n 除以 b) 加 f(n)，其中 a 是子问题个数，b 是规模缩小比例，f(n) 是分解与合并的代价。把 f(n) 和 n 的以 b 为底 a 的对数次方比较：f(n) 更小则总代价由叶子决定，取 n 的 log 次方；两者同阶则再乘一个 log n；f(n) 更大则直接取 f(n)。\n- 归并排序：a 等于 2、b 等于 2、f(n) 是 O(n)，与 n 的一次方同阶，所以是 O(n log n)。\n- 二分查找：a 等于 1、b 等于 2、f(n) 是 O(1)，叶子主导，所以是 O(log n)。\n- 二叉树遍历：a 等于 2、b 等于 2、f(n) 是 O(1)，叶子主导，得到 O(n)。\n注意主定理不是万能的：子问题规模不相等（比如每次只减一的斐波那契式递归）、f(n) 不是多项式量级时都不适用，这时改用递归树或代入法。另外 a、b 必须是常数，划分要均匀，否则结论不成立。",
    points: ["写出 T(n) 等于 aT(n/b) 加 f(n)", "比较 f(n) 与 n 的 log 次方", "三种情况分别对应哪类算法"],
    follow: "递归式 T(n) 等于 2T(n/2) 加 n log n 的复杂度是多少",
    sources: [{ repo: "hello-algo", path: "docs/chapter_computational_complexity/" }, { repo: "CS-Notes", path: "docs/" }],
  },
];
