// 面试题库 · 算法 · 数组 / 字符串 / 链表 / 树 / 搜索。
// 本文件是「面试刷题」工具的纯数据模块，导出 ALGO_A_QUESTIONS 供题库页按 topic / difficulty / tags 过滤渲染，
// 覆盖数组与矩阵、字符串、链表、二叉树、二分与搜索五个主题，每题都配 3 条自评要点与 1 条追问，偏重机制理解而非背代码。
// 出处约定：每条题目的 sources 只写仓库 key 与仓库内相对路径前缀，不写完整 URL，由界面侧拼回可点开的深链；
// 可选仓库固定为 leetcode-master / hello-algo / fucking-algorithm / azl397985856-leetcode / CS-Notes，路径必须真实存在。
export const ALGO_A_QUESTIONS = [
  {
    id: "algo-a-array-spiral-matrix",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 2,
    tags: ["矩阵", "模拟", "边界"],
    question: "螺旋矩阵：四条边的边界怎么处理才不重不漏？",
    answer:
      "结论：螺旋遍历不靠公式，靠 top、bottom、left、right 四个边界变量，每走完一条边就把它内缩一格，直到两条边界交叉。\n\n机制：\n- 顺序固定：从左到右走 top 行，从上到下走 right 列，从右到左走 bottom 行，从下到上走 left 列，走完一条边就把对应边界内移一格。\n- 时间 O(m×n)：每个格子恰好访问一次；空间 O(1)，除结果数组外只用四个变量。\n- 后两条边必须再判一次边界是否交叉，否则行列不相等时中间那行或那列会被重复写入。\n\n实践与排查：典型 bug 是「走完上边和右边后，下边与左边的起点已经被前两步改过」。写完先拿 1×n 与 m×1 两种极端输入手推一遍。\n```python\ntop, bottom, left, right = 0, len(mat) - 1, 0, len(mat[0]) - 1\nwhile top <= bottom and left <= right:\n    for j in range(left, right + 1): res.append(mat[top][j])\n    top += 1\n    for i in range(top, bottom + 1): res.append(mat[i][right])\n    right -= 1\n    if top <= bottom:\n        for j in range(right, left - 1, -1): res.append(mat[bottom][j])\n        bottom -= 1\n    if left <= right:\n        for i in range(bottom, top - 1, -1): res.append(mat[i][left])\n        left += 1\n```",
    points: ["用四个边界变量控制四条边", "每走完一条边就内缩一格", "最后两条边要再判一次越界"],
    follow: "如果要求按逆时针螺旋遍历，代码要改哪几行？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-a-array-rotate-inplace",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 2,
    tags: ["矩阵", "原地", "旋转"],
    question: "矩阵顺时针旋转 90 度，怎么做到原地且不用额外空间？",
    answer:
      "结论：顺时针旋转 90 度等于「先转置，再把每一行左右翻转」。转置把下标 (i, j) 换到 (j, i)，行翻转把列下标 j 映射成 n 减 1 减 j，两步复合正好落在目标位置 (j, n-1-i)。\n\n机制：\n- 转置只需遍历上三角，交换 matrix[i][j] 与 matrix[j][i]；遍历整个矩阵会把元素换回去。\n- 时间 O(n²)：每个元素参与两次常数级交换；空间 O(1)，全程原地，这就是它比新建矩阵优秀的地方。\n- 逆时针旋转是「先转置，再上下翻转」，顺序不能反，先翻转再转置得到的是另一条对角线的镜像。\n\n实践与排查：内层循环从 i 加 1 开始而不是从 0 开始，这是最常见的错。若题目允许返回新矩阵，直接按新矩阵的 (j, n-1-i) 等于原矩阵的 (i, j) 一次成型更直观。\n```python\nn = len(matrix)\nfor i in range(n):\n    for j in range(i + 1, n):\n        matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]\nfor row in matrix:\n    row.reverse()\n```",
    points: ["旋转等于转置加行翻转两步复合", "转置只遍历上三角避免换回去", "逆时针是先转置再上下翻转"],
    follow: "如果矩阵不是方阵，先转置再翻转还成立吗？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-a-array-sliding-window-template",
    category: "algo",
    topic: "数组与矩阵",
    difficulty: 1,
    tags: ["双指针", "滑动窗口", "模板"],
    question: "双指针和滑动窗口的通用模板是什么，什么时候能收缩左边界？",
    answer:
      "结论：模板是「右指针扩张、满足条件后左指针收缩并更新答案」。看着是两层循环，但两个指针都只向右移，总复杂度仍是 O(n)。\n\n机制：\n- 外层 for 移动 right 把新元素纳入窗口，内层 while 在窗口仍然合法时移动 left 去尝试更优解。\n- 时间 O(n)：left 与 right 各自最多走 n 步，内层执行的总次数不超过 n，所以不是 O(n²)。\n- 空间 O(k)：k 是窗口状态的大小，用哈希表或计数数组维护。\n- 能用滑动窗口的前提是单调性：扩张让指标单调变好、收缩让它单调变差。含负数的子数组和就不满足，只能退回前缀和加哈希。\n\n实践与排查：动手前先写清三件事——窗口里维护什么状态、什么条件下收缩、答案在扩张时更新还是收缩时更新。这三条定下来，代码基本不会错。\n```python\nleft, best = 0, 0\nwindow = dict()\nfor right, c in enumerate(s):\n    window[c] = window.get(c, 0) + 1\n    while window[c] > 1:            # 出现重复就收缩\n        window[s[left]] -= 1\n        left += 1\n    best = max(best, right - left + 1)\nreturn best\n```",
    points: ["右指针扩张、左指针收缩的骨架", "两指针都单调右移所以是 O(n)", "能用窗口的前提是指标单调"],
    follow: "如果题目改成求最短的满足条件的子数组，模板要怎么变？",
    sources: [{ repo: "fucking-algorithm", path: "高频面试系列/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-a-string-kmp-next",
    category: "algo",
    topic: "字符串",
    difficulty: 3,
    tags: ["KMP", "字符串匹配", "前缀表"],
    question: "KMP 的 next 数组到底在做什么，它为什么能避免回溯主串指针？",
    answer:
      "结论：next 数组记录的是模式串每个前缀的「最长相等前后缀长度」。失配时它告诉模式串该退到哪一位继续比，主串指针永不回退。\n\n机制：\n- 主串指针 i 只增不减；模式串指针 j 失配时退到 next[j-1]，因为已匹配的那段后缀同时也是前缀，这段前缀不必再比一次。\n- 时间 O(n+m)：求 next 与匹配各一趟线性，j 每次最多加一，回退总量不超过它增加的总量。\n- 空间 O(m)：next 长度等于模式串长度，这也是它比暴力匹配多付出的唯一代价。\n\n实践与排查：next 有两种流派——统一减一的前缀表与不减一的，混用会死循环或漏匹配，动手前先确认题目用哪种。求 next 的过程本身就是模式串自己和自己匹配，所以两段代码形状几乎一样。next[0] 必须是 0，退到 0 仍失配就只移动 i。\n```python\ndef build_next(p):\n    nxt = [0] * len(p)\n    j = 0\n    for i in range(1, len(p)):\n        while j > 0 and p[i] != p[j]:\n            j = nxt[j - 1]\n        if p[i] == p[j]:\n            j += 1\n        nxt[i] = j\n    return nxt\n```",
    points: ["next 是最长相等前后缀长度", "失配时只退模式串指针", "主串指针不回退，整体 O(n+m)"],
    follow: "如果模式串很长而主串很短，KMP 还划算吗？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-a-string-longest-palindrome",
    category: "algo",
    topic: "字符串",
    difficulty: 2,
    tags: ["回文", "动态规划", "中心扩展"],
    question: "最长回文子串：中心扩展和动态规划两种解法，怎么选？",
    answer:
      "结论：优先中心扩展，O(n²) 时间、O(1) 空间，写法短常数小；动态规划时间同为 O(n²) 却要 O(n²) 空间，只有需要判断「任意子串是否回文」时才划算。\n\n机制：\n- 中心扩展：回文关于中心对称，枚举 2n 减 1 个中心（含两字符之间的空隙），从中心向两边扩，扩不动就停。\n- 动态规划：用二维布尔表表示 s[i..j] 是否回文，转移条件是两端字符相等且内部回文，必须按子串长度递增枚举，否则会读到还没算的状态。\n- 两者时间都是 O(n²)，因为最坏要枚举 O(n²) 个子串；Manacher 能压到 O(n)，面试里通常只要求说清思路。\n\n实践与排查：中心分奇数与偶数两类，只写一类会漏掉偶数长度回文，例如 bb。用「扩展函数返回长度、最后统一切片」的写法，比一边扩一边记起止下标更不容易错。\n```python\ndef expand(s, l, r):\n    while l >= 0 and r < len(s) and s[l] == s[r]:\n        l -= 1\n        r += 1\n    return l + 1, r - 1\n\nbest = (0, 0)\nfor c in range(len(s)):\n    for l, r in (expand(s, c, c), expand(s, c, c + 1)):\n        if r - l > best[1] - best[0]:\n            best = (l, r)\nreturn s[best[0]:best[1] + 1]\n```",
    points: ["中心扩展 O(1) 空间更实用", "动态规划要按长度递增枚举", "中心有奇偶两类，共 2n 减 1 个"],
    follow: "如果要求 O(n) 时间，Manacher 的核心思想是什么？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "高频面试系列/" }],
  },
  {
    id: "algo-a-string-reverse-words",
    category: "algo",
    topic: "字符串",
    difficulty: 1,
    tags: ["字符串", "反转", "原地"],
    question: "反转字符串里的单词：怎么做到原地并去掉多余空格？",
    answer:
      "结论：三步——先整体反转，再逐词反转回来，最后用读写双指针把多余空格挤掉。整体反转会颠倒单词顺序，同时把每个单词自身也倒过来，逐词再反转一次正好复原单词内部顺序。\n\n机制：\n- 整体反转一趟 O(n)，逐词反转合计 O(n)，压缩空格一趟 O(n)，总时间 O(n)；空间 O(1)，全部在原字符数组上交换。\n- 若允许额外空间，按空格切分后过滤空串再倒序拼接是 O(n) 空间，代码更短但在大输入上有额外分配。\n\n实践与排查：去空格必须原地压缩，而不是每次删除都搬移后面所有字符，那样会退化成 O(n²)。前导空格、尾随空格、词间连续空格三种情况都要覆盖，拿「两个空格开头、词间三空格」的输入验一遍。多数语言字符串不可变，先转成字符数组再动手。\n```python\ndef reverse_range(a, i, j):\n    while i < j:\n        a[i], a[j] = a[j], a[i]\n        i, j = i + 1, j - 1\n\nreverse_range(a, 0, n - 1)          # 1. 整体反转\ni = 0                               # 2. 逐词反转\nwhile i < n:\n    if a[i] != ' ':\n        j = i\n        while j + 1 < n and a[j + 1] != ' ':\n            j += 1\n        reverse_range(a, i, j)\n        i = j + 1\n    else:\n        i += 1\nw = 0                               # 3. 原地压缩空格\nfor i in range(n):\n    if a[i] != ' ':\n        if w and a[w - 1] != ' ':\n            a[w] = ' '\n            w += 1\n        a[w] = a[i]\n        w += 1\na[:] = a[:w]\n```",
    points: ["整体反转再逐词反转复原顺序", "读写双指针原地压缩空格", "覆盖前导尾随与词间多空格"],
    follow: "如果要求只反转每个单词本身、不改变单词顺序呢？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-a-linked-list-reverse-k-group",
    category: "algo",
    topic: "链表",
    difficulty: 3,
    tags: ["链表", "翻转", "指针"],
    question: "K 个一组翻转链表：怎么在 O(1) 空间里处理不足 K 个的尾巴？",
    answer:
      "结论：先数够 K 个再翻，不够就停。用哨兵节点指向头，每轮从当前段的前驱开始，把这 K 个节点按头插法反转，再把反转后的段尾接到下一段。\n\n机制：\n- 每轮先走 K 步探测长度，够就反转这一段，不够直接结束，尾巴保持原样，这是本题唯一的特判。\n- 时间 O(n)：每个节点在探测与反转里各被访问常数次；空间 O(1)，只用哨兵和几个指针。\n- 用递归写虽然短，但栈深度是 n 除以 K，空间退化成 O(n/K)，面试里常被追问这一点。\n\n实践与排查：反转前必须记住这一段的头（反转后变尾）和下一段的起点，否则链表会断。内层反转执行 K 减 1 次而不是 K 次，多翻一次会把下一组的头也串进来。最后返回哨兵的 next，而不是原来的 head。\n```python\ndummy = ListNode(0, head)\ngroup_prev = dummy\nwhile True:\n    kth = group_prev\n    for _ in range(k):\n        kth = kth.next\n        if not kth:\n            return dummy.next\n    group_next = kth.next\n    prev, cur = group_next, group_prev.next\n    while cur is not group_next:        # 头插法反转这一段\n        nxt = cur.next\n        cur.next = prev\n        prev, cur = cur, nxt\n    tail = group_prev.next              # 反转后的段尾\n    group_prev.next = kth\n    group_prev = tail\n```",
    points: ["先探测够不够 K 个再翻", "头插法反转每段并接回前驱", "内层反转只做 K 减 1 次"],
    follow: "如果不足 K 个也要反转，代码要改哪一处？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-a-linked-list-merge-k-sorted",
    category: "algo",
    topic: "链表",
    difficulty: 3,
    tags: ["链表", "堆", "分治"],
    question: "合并 K 个有序链表：堆和分治各自的复杂度与取舍是什么？",
    answer:
      "结论：两者时间同为 O(N log K)，N 是总节点数；堆用 O(K) 空间，分治只用 O(log K) 的递归栈。堆实现更短，分治常数更小，也天然适合并行与外部归并。\n\n机制：\n- 小顶堆里始终只放每条链表的当前头节点，弹出最小的接到结果尾部，再把它的后继入堆。堆大小不超过 K，每次操作 log K，共 N 次。\n- 分治是两两合并：第 i 轮之后每条链长度翻倍，共 log K 轮，每轮所有节点被比较常数次，合计 O(N log K)。\n- 逐个合并的朴素做法是 O(NK)，K 大时明显退化，这是最常见的错误答案，一定要主动说明为什么不用它。\n\n实践与排查：Python 的堆比较元组，节点值相同时会比较第二个元素，若第二个是节点对象会直接抛类型错误，所以要存一个下标做二次比较。入堆前先过滤空链表，否则会在堆里塞进 None。\n```python\nimport heapq\n\ndef merge_k(lists):\n    heap = [(node.val, i, node) for i, node in enumerate(lists) if node]\n    heapq.heapify(heap)\n    dummy = tail = ListNode(0)\n    while heap:\n        val, i, node = heapq.heappop(heap)\n        tail.next = node\n        tail = node\n        if node.next:\n            heapq.heappush(heap, (node.next.val, i, node.next))\n    return dummy.next\n```",
    points: ["堆里只放每条链表的当前头节点", "堆与分治都是 O(N log K)", "逐个合并是 O(NK)，要说明不取"],
    follow: "如果 K 条链表总长度极大、内存放不下，怎么做外部归并？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_heap/" }],
  },
  {
    id: "algo-a-linked-list-copy-random-pointer",
    category: "algo",
    topic: "链表",
    difficulty: 2,
    tags: ["链表", "深拷贝", "哈希表"],
    question: "复制带随机指针的链表：怎么在 O(1) 额外空间里完成深拷贝？",
    answer:
      "结论：把新节点直接插在原节点后面，用原节点的 next 当索引找到它的副本，最后把交替的两条链拆开。哈希表法要 O(n) 空间，这个原地编织法把额外空间降到 O(1)。\n\n机制：\n- 第一步遍历，为每个节点创建副本并插到它后面，形成 A、A撇、B、B撇的交替结构。\n- 第二步设 random：原节点 cur 的副本就是 cur.next，副本的 random 就是 cur.random.next，因为副本一定紧跟原节点。\n- 第三步拆链，把交替结构还原成两条独立链表。三步都是 O(n) 时间，额外空间 O(1)。\n\n实践与排查：random 为空要单独判，否则 cur.random.next 直接空指针。拆链时原链表的 next 也必须还原，只拆新链会破坏输入数据。面试里哈希表法更容易一次写对，可以先讲哈希表再优化到原地。\n```python\ncur = head\nwhile cur:                          # 1. 编织交替链\n    cur.next = Node(cur.val, cur.next, None)\n    cur = cur.next.next\ncur = head\nwhile cur:                          # 2. 接上 random\n    if cur.random:\n        cur.next.random = cur.random.next\n    cur = cur.next.next\ndummy = Node(0)\ncopy_cur, cur = dummy, head\nwhile cur:                          # 3. 拆成两条链\n    copy_cur.next = cur.next\n    cur.next = cur.next.next\n    copy_cur, cur = copy_cur.next, cur.next\nreturn dummy.next\n```",
    points: ["副本插在原节点后面形成交替链", "副本 random 就是原 random 的 next", "拆链时要还原原链表的 next"],
    follow: "如果链表还带一个指向父节点的指针，复制时要额外注意什么？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "fucking-algorithm", path: "数据结构/" }],
  },
  {
    id: "algo-a-tree-max-path-sum",
    category: "algo",
    topic: "二叉树",
    difficulty: 3,
    tags: ["二叉树", "递归", "后序遍历"],
    question: "二叉树的最大路径和：为什么必须在后序位置更新答案？",
    answer:
      "结论：递归函数返回的是「以当前节点为端点、向下延伸的单边最大和」，而全局答案在「左单边加右单边加当前值」里取最大。单边才能继续往上接，双边到当前节点就拐弯结束了，两者必须分开。\n\n机制：\n- 只有在后序位置才能同时拿到左右子树的结果，先序位置拿不到，这就是必须后序的原因。\n- 单边贡献为负数时取 0，等价于不选这条子树，否则会把答案越拖越小。\n- 时间 O(n)：每个节点访问一次；空间 O(h)：递归栈深度等于树高，树退化成链时是 O(n)。\n\n实践与排查：答案初值要设成负无穷而不是 0，节点全为负数时正确答案是最大的那个负数，设 0 会得到错误结果。求直径是同一套骨架，把「和」换成「深度加深度」，答案换成边数最大值。\n```python\nbest = float('-inf')\n\ndef gain(node):\n    global best\n    if not node:\n        return 0\n    left = max(gain(node.left), 0)\n    right = max(gain(node.right), 0)\n    best = max(best, node.val + left + right)   # 拐弯的路径\n    return node.val + max(left, right)          # 继续向上的单边\n```",
    points: ["递归返回向下的单边最大和", "答案在左右单边加当前值处更新", "负数单边取 0，初值设负无穷"],
    follow: "如果要求返回最大路径和对应的具体路径，怎么做？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_tree/" }],
  },
  {
    id: "algo-a-tree-build-preorder-inorder",
    category: "algo",
    topic: "二叉树",
    difficulty: 2,
    tags: ["二叉树", "递归", "分治"],
    question: "从前序与中序序列构造二叉树：怎么定位根并切分左右子树？",
    answer:
      "结论：前序的第一个元素是根，拿这个值去中序里定位，中序中它左边是左子树、右边是右子树；再按左子树的节点个数去前序里切出两段，递归下去。\n\n机制：\n- 定位根用哈希表把中序的值到下标的映射预先存好，避免每层线性查找，这是把 O(n²) 降到 O(n) 的关键。\n- 时间 O(n)：每个节点只建一次；空间 O(n)：哈希表加递归栈，树退化成链时栈深为 n。\n- 前序加中序、后序加中序都能唯一确定一棵树；前序加后序不能，因为分不清只有一个孩子时它在左还是在右。\n\n实践与排查：切分下标最容易错，建议只用一个「左子树长度」变量推出其余所有边界，并在注释里写死区间是闭区间还是左闭右开。中序里找不到根说明输入非法，要显式报错而不是静默返回空。\n```python\ndef build(pre, ino):\n    index = dict((v, i) for i, v in enumerate(ino))\n\n    def helper(pl, pr, il, ir):\n        if pl > pr:\n            return None\n        root = TreeNode(pre[pl])\n        k = index[pre[pl]]\n        size = k - il                       # 左子树节点个数\n        root.left = helper(pl + 1, pl + size, il, k - 1)\n        root.right = helper(pl + size + 1, pr, k + 1, ir)\n        return root\n\n    return helper(0, len(pre) - 1, 0, len(ino) - 1)\n```",
    points: ["前序首元素就是根", "用哈希表定位根在中序的下标", "按左子树长度推出全部边界"],
    follow: "如果只给前序和后序序列，能唯一确定这棵树吗？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_divide_and_conquer/" }],
  },
  {
    id: "algo-a-tree-bst-operations",
    category: "algo",
    topic: "二叉树",
    difficulty: 1,
    tags: ["二叉搜索树", "中序遍历", "删除"],
    question: "二叉搜索树的查找、插入、删除分别怎么写，删除为什么最难？",
    answer:
      "结论：查找与插入都是沿一条路径比较大小往下走；删除最难，因为删掉有两个孩子的节点后必须找人接班——用中序后继（右子树最小值）替换它的值，再递归删掉那个后继。\n\n机制：\n- 三种操作的时间都是 O(h)，h 是树高；平衡时是 O(log n)，退化成链时是 O(n)，这就是要引入平衡树的原因。\n- 空间 O(h)：递归栈深度；查找改成迭代写可以把空间降到 O(1)。\n- 删除分三类：叶子直接删，只有一个孩子就用孩子顶替，有两个孩子则用后继替换值后再删后继。后继一定没有左孩子，所以第三类会退化成前两类。\n\n实践与排查：中序遍历有序是 BST 一切操作的依据。校验一棵树是否合法 BST 必须传上下界递归判断，只比较父子会漏掉「右子树里的最小值仍小于根」这类反例。\n```python\ndef delete(root, key):\n    if not root:\n        return None\n    if key < root.val:\n        root.left = delete(root.left, key)\n    elif key > root.val:\n        root.right = delete(root.right, key)\n    else:\n        if not root.left:\n            return root.right\n        if not root.right:\n            return root.left\n        succ = root.right\n        while succ.left:                # 找中序后继\n            succ = succ.left\n        root.val = succ.val\n        root.right = delete(root.right, succ.val)\n    return root\n```",
    points: ["查找插入沿一条路径比较大小", "删除两个孩子用中序后继替换", "中序遍历有序是判断依据"],
    follow: "如果 BST 频繁插入删除，怎么保证不退化成链表？",
    sources: [{ repo: "hello-algo", path: "docs/chapter_tree/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-a-search-binary-boundaries",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 1,
    tags: ["二分查找", "边界", "死循环"],
    question: "二分的三种边界写法有什么区别，什么时候会死循环？",
    answer:
      "结论：三种写法分别是闭区间、左闭右开、开区间，区别只在初始边界、while 条件以及收缩时要不要加减一。死循环的根源只有一个：区间没有真正变小，也就是 mid 始终等于 left。\n\n机制：\n- 闭区间用 while left 小于等于 right，收缩写 left 等于 mid 加一、right 等于 mid 减一，循环结束时 left 就是第一个大于目标的位置。\n- 左闭右开用 while left 小于 right，收缩写 right 等于 mid，此时 mid 必须取左中位数；取右中位数会让只差一时的区间原地打转。\n- 时间 O(log n)：每次迭代区间长度减半；空间 O(1)，只用常数个变量。\n\n实践与排查：动手前先定死两件事——区间是闭还是开、要返回第一个还是最后一个满足条件的位置，这两个约定决定了所有加减一。mid 写成 left 加 (right 减 left) 除以 2，既避免相加溢出，也保证区间每次至少缩小一格。\n```python\n# 闭区间写法：找第一个 >= target 的位置\nleft, right = 0, len(nums) - 1\nwhile left <= right:\n    mid = left + (right - left) // 2\n    if nums[mid] < target:\n        left = mid + 1\n    else:\n        right = mid - 1\nreturn left        # 循环结束时 left 即插入点\n```",
    points: ["三种写法的区别在区间开闭", "死循环源于区间没有变小", "统一返回第一个满足条件的位置"],
    follow: "如果数组里有重复元素，找第一个和最后一个位置怎么写？",
    sources: [{ repo: "hello-algo", path: "docs/chapter_searching/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-a-search-rotated-array",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 2,
    tags: ["二分查找", "旋转数组", "边界"],
    question: "搜索旋转排序数组：怎么判断哪一半是有序的？",
    answer:
      "结论：取中点后，左半段与右半段里必有一半是有序的。用这一半的两个端点判断目标在不在其中：在就进这一半，不在就去另一半。\n\n机制：\n- 判断有序用 nums[left] 小于等于 nums[mid]；相等时区间只剩一到两个元素，边界照常收缩仍能收敛。\n- 时间 O(log n)：每轮排除一半；空间 O(1)。相比先二分找旋转点、再二分查找的两趟写法，这一版一次遍历、分支更少。\n- 有重复元素时，两端与中点三者相等会无法判断哪边有序，只能退化成 left 加一、right 减一，最坏 O(n)。\n\n实践与排查：两个分支里「目标是否落在有序半边」的条件最容易写反。诀窍是先确定有序半边的闭区间端点，再写目标落在区间内的条件，最后统一在循环外返回负一。\n```python\nleft, right = 0, len(nums) - 1\nwhile left <= right:\n    mid = left + (right - left) // 2\n    if nums[mid] == target:\n        return mid\n    if nums[left] <= nums[mid]:                 # 左半有序\n        if nums[left] <= target < nums[mid]:\n            right = mid - 1\n        else:\n            left = mid + 1\n    else:                                       # 右半有序\n        if nums[mid] < target <= nums[right]:\n            left = mid + 1\n        else:\n            right = mid - 1\nreturn -1\n```",
    points: ["一半必有序，用它判断目标在哪边", "每轮排除一半，时间 O(log n)", "有重复元素时最坏退化到 O(n)"],
    follow: "如果数组允许重复元素，还能保持 O(log n) 吗？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "hello-algo", path: "docs/chapter_searching/" }],
  },
  {
    id: "algo-a-search-sorted-matrix-kth",
    category: "algo",
    topic: "二分与搜索",
    difficulty: 2,
    tags: ["二分答案", "矩阵", "堆"],
    question: "有序矩阵中第 K 小的元素：二分答案的思路怎么用？",
    answer:
      "结论：不在矩阵上二分位置，而是二分「答案的数值」。拿最小值与最大值作为数值区间做二分，对每个候选值数出矩阵里不大于它的元素个数，个数达到 K 就说明答案不超过它。\n\n机制：\n- 计数利用行列都递增的性质，从左下角出发：当前值不大于候选值就整列计数并右移，否则上移，单次计数 O(m+n)。\n- 时间 O((m+n) log(max-min))：外层二分值域，内层线性计数；空间 O(1)。\n- 作为对比，用小顶堆做 K 路归并是 O(K log m)，K 接近元素总数时远不如二分答案，这就是二分答案的价值。\n\n实践与排查：收敛条件写 left 小于 right，最后返回 left。候选值取真实值域而不是下标范围，否则计数会落空。计数用「不大于」而不是「小于」，才能保证收敛到矩阵里真实存在的那个元素上。\n```python\ndef kth(mat, k):\n    n = len(mat)\n    lo, hi = mat[0][0], mat[n - 1][n - 1]\n    while lo < hi:\n        mid = lo + (hi - lo) // 2\n        cnt, row, col = 0, n - 1, 0\n        while row >= 0 and col < n:          # 从左下角数不大于 mid 的个数\n            if mat[row][col] <= mid:\n                cnt += row + 1\n                col += 1\n            else:\n                row -= 1\n        if cnt < k:\n            lo = mid + 1\n        else:\n            hi = mid\n    return lo\n```",
    points: ["二分的是答案数值不是下标", "从左下角统计不大于的元素个数", "复杂度 O((m+n) log 值域)"],
    follow: "如果矩阵的行列长度差很多，堆和二分答案哪个更合适？",
    sources: [{ repo: "leetcode-master", path: "problems/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
];
