// 面试题库 · 算法 B 卷：动态规划 / 回溯 / 贪心 / 图论 / 排序 / 数据结构设计。
// 本文件是「面试刷题」工具的离线题库数据源之一，只导出纯数据、无副作用，由工具页按 topic / difficulty / tags 过滤渲染，用于自测自评。
// 出处约定：每条题目的 sources 标注参考答案的来源仓库与仓库内相对路径，repo 只能取固定枚举
// （leetcode-master / hello-algo / fucking-algorithm / azl397985856-leetcode / CS-Notes），path 必须是该仓库里真实存在的前缀，仅作学习引用。
export const ALGO_B_QUESTIONS = [
  {
    id: "algo-b-dp-stock-series",
    category: "algo",
    topic: "动态规划",
    difficulty: 3,
    tags: ["DP", "状态机", "股票"],
    question: "买卖股票系列：怎么用状态机统一处理冷冻期和手续费",
    answer: "把每天收盘后的状态压缩成两种：持有股票和不持有股票，用两个变量表示对应的最大收益。这样冷冻期、手续费、最多 k 次交易都只是转移方程上的小改动，不用另起一套思路。\n- 时间 O(n)：每天只做常数次状态转移。\n- 空间 O(1)：两个变量滚动，不需要二维表。\n易错点：持有状态的初值要写成负的 prices[0] 而不是 0，否则相当于白拿一只股票；有冷冻期时买入要从两天前的不持有状态转移过来；手续费只在买入或卖出单边扣，两边都扣会重复计算；允许当天买卖时不要画蛇添足加限制。\n```python\nhold, free = -prices[0], 0\nfor p in prices[1:]:\n    hold, free = max(hold, free - p), max(free, hold + p)\nreturn free\n```",
    points: ["定义持有与不持有两个状态", "转移只依赖前一天，可压成常数空间", "手续费只在单边扣，冷冻期会错一天"],
    follow: "如果限制最多交易 k 次，状态要再加一维，具体怎么设计",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }],
  },
  {
    id: "algo-b-dp-house-robber",
    category: "algo",
    topic: "动态规划",
    difficulty: 1,
    tags: ["DP", "滚动数组", "环形数组"],
    question: "打家劫舍：环形数组版本比线性版本多处理了什么",
    answer: "线性版本定义状态为前 i 间房能偷到的最大金额，第 i 间只有偷与不偷两种选择：不偷就继承前一个状态，偷就要跳过第 i-1 间，取前两个状态加上当前金额。环形版本首尾相邻，等价于第一间和最后一间不能同时偷，于是拆成两个线性子问题分别求解再取较大值。\n- 时间 O(n)：两段各扫一遍。\n- 空间 O(1)：只保留前两个状态，滚动更新。\n易错点：只有一间房时两段子数组都是空的，必须单独返回第一间；两段的区间是左闭右开，分别是零到 n-1 和一到 n，写成闭区间等于首尾又相邻了。\n```python\ndef rob(seg):\n    prev = cur = 0\n    for x in seg:\n        prev, cur = cur, max(cur, prev + x)\n    return cur\nreturn max(rob(nums[:-1]), rob(nums[1:])) if len(nums) > 1 else nums[0]\n```",
    points: ["不偷就继承，偷就跳过前一间", "环形拆成两段线性问题取较大值", "只有一间房时两段为空要特判"],
    follow: "如果房间排成二叉树结构，怎么改成树形 DP",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-dp-lcs-edit-distance",
    category: "algo",
    topic: "动态规划",
    difficulty: 2,
    tags: ["DP", "字符串", "二维DP"],
    question: "最长公共子序列和编辑距离的状态定义差在哪",
    answer: "两者状态定义几乎一样，都表示第一个串前 i 个字符与第二个串前 j 个字符的答案。差别在转移：最长公共子序列只在字符相等时用左上加一，不相等就取上方与左方的较大值，含义是放弃其中一个字符；编辑距离在字符不相等时要取删除、插入、替换三者的最小值再加一，相等时直接继承左上而不加代价。\n- 时间 O(m·n)：两层循环，每个格子常数次比较。\n- 空间 O(m·n)：可滚动成一维，但要额外变量暂存会被覆盖的左上值。\n易错点：编辑距离的边界不是零，第一行和第一列分别是 j 和 i，代表一直插入；下标从 1 开始，取字符要用 i-1，否则会错位或越界。\n```python\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if a[i-1] == b[j-1]:\n            dp[i][j] = dp[i-1][j-1] + 1\n        else:\n            dp[i][j] = max(dp[i-1][j], dp[i][j-1])\n```",
    points: ["状态都是两个前缀之间的答案", "相等时都用左上，不等时处理不同", "编辑距离边界是 i 和 j 不是零"],
    follow: "为什么编辑距离不能像最长公共子序列那样只取最大值",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "hello-algo", path: "docs/chapter_dynamic_programming/" }],
  },
  {
    id: "algo-b-dp-interval-balloon",
    category: "algo",
    topic: "动态规划",
    difficulty: 3,
    tags: ["区间DP", "戳气球", "记忆化"],
    question: "戳气球为什么要定义成开区间，再按区间长度枚举",
    answer: "顺着先戳哪个去想，子问题会被切成互相影响的两段，因为左右邻居一直在变。反过来定义状态为开区间内全部戳完、只剩两端时的最大得分，两端始终存在，于是枚举最后一个被戳的气球就能把区间拆成互不干扰的两半。数组两端各补一个 1，让边界气球也有邻居，统一处理。\n- 时间 O(n³)：状态 O(n²)，每个状态还要枚举分割点。\n- 空间 O(n²)：二维 dp 表。\n易错点：必须按区间长度从小到大递推，保证子区间已经算好；分割点取开区间内部，两端不算；补 1 后原数组下标整体右移一位，答案是零到 n-1 这个区间。\n```python\nval = [1] + nums + [1]\nn = len(val)\ndp = [[0] * n for _ in range(n)]\nfor length in range(2, n):\n    for i in range(n - length):\n        j = i + length\n        for k in range(i + 1, j):\n            dp[i][j] = max(dp[i][j], dp[i][k] + val[i] * val[k] * val[j] + dp[k][j])\nreturn dp[0][n - 1]\n```",
    points: ["定义开区间戳完的最大得分", "枚举最后一个被戳的气球拆分区间", "按区间长度递推，两端各补一个 1"],
    follow: "如果还要输出具体的戳气球顺序，DP 里怎么记录决策",
    sources: [{ repo: "fucking-algorithm", path: "动态规划/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-backtracking-subsets-permutations",
    category: "algo",
    topic: "回溯",
    difficulty: 3,
    tags: ["回溯", "去重", "模板"],
    question: "子集、组合、排列三类回溯模板的差异在哪，怎么去重",
    answer: "三者骨架都是做选择、递归、撤销选择，差别在枚举起点和收集时机。子集与组合用 start 参数保证只往后选，天然不产生顺序不同造成的重复；子集在每个节点都收集答案，组合通常到叶子才收集。排列每层从头遍历，必须用 used 数组跳过已选元素。输入含重复元素时先排序，再在同一层跳过与前一个相同的分支。\n- 时间 O(n·2^n) 与 O(n·n!)：分别对应子集、排列的数量乘以拷贝路径的代价。\n- 空间 O(n)：递归栈加 used 数组，不计结果集。\n易错点：同层去重的条件是下标大于 start 且当前值等于前一个值，用 continue 而不是 break；撤销选择要和做选择严格对称，漏一步结果就会串味。\n```python\ndef dfs(start, path):\n    res.append(path[:])\n    for i in range(start, len(nums)):\n        if i > start and nums[i] == nums[i-1]:\n            continue\n        path.append(nums[i])\n        dfs(i + 1, path)\n        path.pop()\n```",
    points: ["子集与组合用 start 控制顺序", "排列用 used 数组标记已选元素", "同层跳过重复值实现去重"],
    follow: "如果要枚举和为 target 的组合且每个数只用一次，模板怎么改",
    sources: [{ repo: "hello-algo", path: "docs/chapter_backtracking/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-backtracking-nqueens",
    category: "algo",
    topic: "回溯",
    difficulty: 2,
    tags: ["回溯", "N皇后", "剪枝"],
    question: "N 皇后回溯：三个方向的冲突检测分别怎么设计",
    answer: "逐行放置，每行只放一个皇后，行冲突自然不存在，只需检测列和两条斜线。列用一个布尔数组；两条斜线分别用行加列、行减列加偏移量做下标，因为同一条斜线上这两个值恒定，一次判断就能覆盖整条线，把检测从遍历降成常数。\n- 时间 O(n!)：第一行 n 种选择，之后逐行被剪枝，实际远小于全排列。\n- 空间 O(n)：三个标记数组加递归栈，棋盘本身不用存。\n易错点：行减列可能为负，必须加偏移量再当下标；递归出口是行号等于 n 时才记录方案；位运算版本用三个整数代替数组，靠位移和按位与检测冲突，常数更小。\n```python\ndef dfs(r):\n    if r == n:\n        res.append(cols[:])\n        return\n    for c in range(n):\n        if col[c] or diag1[r + c] or diag2[r - c + n - 1]:\n            continue\n        col[c] = diag1[r + c] = diag2[r - c + n - 1] = True\n        cols.append(c)\n        dfs(r + 1)\n        cols.pop()\n        col[c] = diag1[r + c] = diag2[r - c + n - 1] = False\n```",
    points: ["逐行放置消除行冲突", "行加列与行减列标记两条斜线", "行减列加偏移量避免负下标"],
    follow: "用位运算的整数代替三个标记数组，冲突检测怎么写",
    sources: [{ repo: "hello-algo", path: "docs/chapter_backtracking/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-greedy-candy-gas",
    category: "algo",
    topic: "贪心",
    difficulty: 3,
    tags: ["贪心", "局部最优", "证明"],
    question: "分发糖果和加油站：怎么判断局部最优能否推出全局最优",
    answer: "判断标准是局部选择会不会让后面的处境变差、需不需要反悔。分发糖果里每个孩子的数量只由相邻评分决定，左右两个方向互不干扰，于是拆成两次遍历，一次保证比左邻分高的多拿，一次保证比右邻分高的多拿，同一位置取两次的较大值。加油站总油量小于总消耗时无解，否则一旦累计油量变负，说明这段区间里任何起点都撑不过去，直接把起点挪到下一站。\n- 时间 O(n)：各扫一到两遍。\n- 空间 O(1)：只用累计量和起点下标。\n易错点：两次遍历要取最大值而不是覆盖，否则会破坏前一次已经满足的约束；加油站的起点更新必须发生在油量归零之后，总和为负要返回 -1。\n```python\ntotal = cur = start = 0\nfor i, (g, c) in enumerate(zip(gas, cost)):\n    cur += g - c\n    total += g - c\n    if cur < 0:\n        start, cur = i + 1, 0\nreturn start if total >= 0 else -1\n```",
    points: ["局部最优不反悔才可用贪心", "糖果左右各扫一遍后取较大值", "加油站累计油量为负就换起点"],
    follow: "分发糖果如果改成环形相邻，两次遍历还够用吗",
    sources: [{ repo: "fucking-algorithm", path: "算法思维/" }, { repo: "hello-algo", path: "docs/chapter_greedy/" }],
  },
  {
    id: "algo-b-greedy-interval-scheduling",
    category: "algo",
    topic: "贪心",
    difficulty: 2,
    tags: ["贪心", "区间调度", "排序键"],
    question: "区间调度类问题怎么选排序键，为什么是按右端点",
    answer: "要选出最多的不重叠区间，按开始时间排会掉进长区间占位的坑。正确贪心是每次选结束最早且与已选区间不冲突的那个：结束越早，留给后面的空间越大，所以这个选择不会让后续变差。用交换论证可以证明，最优解里的第一个区间总能换成结束最早的那个而不减少总数。\n- 时间 O(n log n)：排序主导，之后一次线性扫描。\n- 空间 O(1)：只记录上一个区间的结束时间。\n易错点：排序键必须是右端点，选左端点或区间长度都是错的；不重叠判定用下一个区间的开始不小于上一个的结束，开闭区间要先和面试官对齐；如果题目是合并区间而不是计数，排序键反而要换成左端点。\n```python\nintervals.sort(key=lambda x: x[1])\ncnt, last = 0, float('-inf')\nfor s, e in intervals:\n    if s >= last:\n        cnt, last = cnt + 1, e\nreturn cnt\n```",
    points: ["按右端点排序，每次选结束最早的", "结束越早留给后面空间越大", "合并区间时排序键要换成左端点"],
    follow: "如果要求用最少数量的箭引爆所有气球，和这题是同一个模型吗",
    sources: [{ repo: "hello-algo", path: "docs/chapter_greedy/" }, { repo: "fucking-algorithm", path: "算法思维/" }],
  },
  {
    id: "algo-b-graph-topological-sort",
    category: "algo",
    topic: "图论",
    difficulty: 2,
    tags: ["拓扑排序", "入度", "判环"],
    question: "拓扑排序的 BFS 和 DFS 两种实现，判环分别怎么做",
    answer: "BFS 版本统计每个点的入度，先把入度为零的点全部入队，出队时把邻居入度减一，减到零就入队；如果最终出队数量少于总点数，说明剩下的点互相依赖，存在环。DFS 版本做后序遍历，访问完所有邻居再把当前点压栈，最后反转；判环靠递归中的三种状态，遇到正在访问中的节点就说明有环。\n- 时间 O(V + E)：每个点和每条边只处理一次。\n- 空间 O(V + E)：邻接表加队列或颜色数组。\n易错点：BFS 判环靠出队计数而不是队列是否为空；DFS 必须有访问中这个中间态，只用布尔数组区分不出环；结果不唯一，要求字典序最小时把队列换成小顶堆。\n```python\nindeg = [0] * n\nfor u in range(n):\n    for v in adj[u]:\n        indeg[v] += 1\nq = deque(i for i in range(n) if indeg[i] == 0)\norder = []\nwhile q:\n    u = q.popleft()\n    order.append(u)\n    for v in adj[u]:\n        indeg[v] -= 1\n        if indeg[v] == 0:\n            q.append(v)\nreturn order if len(order) == n else []\n```",
    points: ["BFS 把入度为零的点入队", "出队数量不足即说明存在环", "DFS 用访问中状态检测环"],
    follow: "如果要输出字典序最小的拓扑序，实现上改哪一处",
    sources: [{ repo: "hello-algo", path: "docs/chapter_graph/" }, { repo: "fucking-algorithm", path: "数据结构/" }],
  },
  {
    id: "algo-b-graph-shortest-path",
    category: "algo",
    topic: "图论",
    difficulty: 3,
    tags: ["最短路径", "Dijkstra", "负权"],
    question: "最短路径算法怎么选：BFS、Dijkstra、Bellman-Ford、Floyd",
    answer: "先看边权和规模。边权全为 1 用 BFS，逐层扩展，第一次到达就是最短。边权非负用 Dijkstra 配小顶堆，每轮取出距离最小的点并松弛邻居，因为距离只会变大，取出的点不可能再被更新。有负权时 Dijkstra 失效，改用 Bellman-Ford 做 V-1 轮全边松弛，还能在第 V 轮检测负环。要求任意两点距离且点数不多时用 Floyd，三重循环、代码短、能处理负权。\n- 时间：BFS 是 O(V+E)，Dijkstra 是 O(E log V)，Bellman-Ford 是 O(VE)，Floyd 是 O(V³)。\n- 空间：前三个都是 O(V) 存距离，Floyd 需要 O(V²) 矩阵。\n易错点：Dijkstra 的正确性依赖已确定的最短距离不会变小，所以不能有负权；稠密图上朴素版本的 O(V²) 反而比堆版本快；Floyd 必须把中间点放在最外层循环。\n```python\ndist = [float('inf')] * n\ndist[src] = 0\npq = [(0, src)]\nwhile pq:\n    d, u = heapq.heappop(pq)\n    if d > dist[u]:\n        continue\n    for v, w in adj[u]:\n        if d + w < dist[v]:\n            dist[v] = d + w\n            heapq.heappush(pq, (d + w, v))\n```",
    points: ["先看边权是否非负与图的规模", "Dijkstra 靠小顶堆加松弛", "负权用 Bellman-Ford，多源用 Floyd"],
    follow: "如果边权只有 0 和 1，能不能比 Dijkstra 更快",
    sources: [{ repo: "hello-algo", path: "docs/chapter_graph/" }, { repo: "azl397985856-leetcode", path: "docs/" }],
  },
  {
    id: "algo-b-sorting-heap-topk",
    category: "algo",
    topic: "排序",
    difficulty: 2,
    tags: ["堆", "TopK", "快速选择"],
    question: "求 TopK 有哪几种解法，堆排序和快速选择怎么取舍",
    answer: "三条路。直接排序后取前 k 个，写法最快，代价 O(n log n)。维护一个大小为 k 的小顶堆，扫描时比堆顶大就替换堆顶，堆里始终是当前最大的 k 个，堆顶恰好是第 k 大，适合数据流或内存放不下全部数据。快速选择借用快排的划分，每次只递归包含目标下标的那一侧，平均线性时间，但会改动原数组且最坏退化。\n- 时间：排序 O(n log n)，堆 O(n log k)，快选平均 O(n)。\n- 空间：堆 O(k)，快选递归栈平均 O(log n)。\n易错点：求第 k 大要用小顶堆，方向反了得到的是第 k 小；快选要随机化基准或三数取中，否则面对有序数组会退化；堆里元素超过 k 就弹出堆顶，弹出的正是堆内最小值。\n```python\nheap = []\nfor x in nums:\n    heapq.heappush(heap, x)\n    if len(heap) > k:\n        heapq.heappop(heap)\nreturn heap[0]\n```",
    points: ["排序、小顶堆、快速选择三条路", "堆法适合数据流与海量数据", "求第 k 大要用小顶堆"],
    follow: "如果数据是持续到来的流，要求随时取中位数，怎么做",
    sources: [{ repo: "hello-algo", path: "docs/chapter_heap/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-sorting-merge-inversion",
    category: "algo",
    topic: "排序",
    difficulty: 2,
    tags: ["归并排序", "逆序对", "链表"],
    question: "归并排序在求逆序对和链表排序上有什么独特价值",
    answer: "归并排序在合并两个有序段时，若右段元素先被取出，说明它比左段剩下的所有元素都小，这些元素每一个都和它构成逆序对，于是能在常数代价里顺手统计总数，这是快排做不到的。链表排序上，归并是唯一能稳定做到 O(n log n) 的排序，自底向上的迭代版本还能把额外空间压到 O(1)，而快排依赖下标划分、堆排依赖随机访问，都不适合链表。\n- 时间 O(n log n)：每层合并总代价 O(n)，共 log n 层。\n- 空间：数组版本需要 O(n) 临时数组，链表迭代版本 O(1)。\n易错点：统计时累加的是左段剩余元素个数，不是加一；相等元素要先取左段才能保持稳定，否则逆序对会被多算；链表找中点后要断开，否则递归不会收敛。\n```python\ndef merge_sort(a, l, r):\n    if r - l <= 1:\n        return 0\n    m = (l + r) // 2\n    cnt = merge_sort(a, l, m) + merge_sort(a, m, r)\n    tmp, i, j = [], l, m\n    while i < m and j < r:\n        if a[i] <= a[j]:\n            tmp.append(a[i])\n            i += 1\n        else:\n            cnt += m - i\n            tmp.append(a[j])\n            j += 1\n    tmp.extend(a[i:m])\n    tmp.extend(a[j:r])\n    a[l:r] = tmp\n    return cnt\n```",
    points: ["合并时右段先出即产生逆序对", "累加的是左段剩余元素个数", "链表只能用归并，快排依赖下标"],
    follow: "如果逆序对定义改成前面的数不小于后面的数，代码要改哪里",
    sources: [{ repo: "hello-algo", path: "docs/chapter_sorting/" }, { repo: "leetcode-master", path: "problems/" }],
  },
  {
    id: "algo-b-design-lru-cache",
    category: "algo",
    topic: "数据结构设计",
    difficulty: 2,
    tags: ["LRU", "双向链表", "哈希表"],
    question: "LRU 缓存为什么要哈希表配双向链表，单链表行不行",
    answer: "哈希表负责常数时间定位节点，双向链表负责常数时间调整顺序：头部是最近使用，尾部是最久未用。命中后把节点摘下来挂到头部；容量满了就删掉尾部节点，并同步从哈希表里删除。必须用双向链表，因为摘除一个已知节点需要它的前驱，单链表拿不到前驱就得花 O(n) 去找，这正是本题的关键取舍。\n- 时间：查询与写入都是 O(1)，哈希定位和链表摘挂都是常数代价。\n- 空间 O(capacity)：节点数不超过容量上限。\n易错点：链表带虚拟头尾哨兵，可以省掉头尾的边界特判；写入已存在的 key 要先更新值再移到头部，不能重复插入；淘汰时忘了删哈希表里的 key，之后会读到已经被移除的节点。\n```python\ndef get(self, key):\n    if key not in self.cache:\n        return -1\n    node = self.cache[key]\n    self.move_to_head(node)\n    return node.val\n```",
    points: ["哈希表定位，双向链表管顺序", "单链表摘节点要 O(n) 找前驱", "淘汰时哈希表与链表要同步删"],
    follow: "如果要求支持并发访问，你会怎么加锁，锁粒度能再细吗",
    sources: [{ repo: "fucking-algorithm", path: "数据结构/" }, { repo: "hello-algo", path: "docs/chapter_array_and_linkedlist/" }],
  },
  {
    id: "algo-b-design-lfu-cache",
    category: "algo",
    topic: "数据结构设计",
    difficulty: 3,
    tags: ["LFU", "频率分桶", "O(1)"],
    question: "LFU 缓存要在常数时间淘汰，除了哈希表还需要哪些结构",
    answer: "LFU 要淘汰访问次数最少的，次数相同时淘汰最久未用的，一张表不够。常见做法是两张哈希表加一组按频率分桶的双向链表：key 到节点的表负责定位；频率到链表桶的表里，每个桶装该频率的全部节点，桶内按最近使用排序；再维护一个最小频率，淘汰时直接取最小频率桶的尾部。访问后把节点从原桶摘下，插入频率加一的桶。\n- 时间：查询与写入都是 O(1)，只有常数次哈希查找和链表摘挂。\n- 空间 O(capacity)：节点数不超过容量，桶数不超过最大访问次数。\n易错点：新节点频率是一，最小频率要重置为一；节点离开最小频率桶后若桶空了，最小频率要加一；更新已存在的 key 也要提升访问频率，不能只改值。\n```python\ndef touch(self, node):\n    f = node.freq\n    self.buckets[f].remove(node)\n    if not self.buckets[f] and self.min_freq == f:\n        self.min_freq += 1\n    node.freq = f + 1\n    self.buckets[node.freq].add_front(node)\n```",
    points: ["两张哈希表加按频率分桶的链表", "维护最小频率实现常数时间淘汰", "新节点频率为一要重置最小频率"],
    follow: "如果要求淘汰策略在 LRU 和 LFU 之间可切换，结构怎么抽象",
    sources: [{ repo: "fucking-algorithm", path: "数据结构/" }, { repo: "CS-Notes", path: "docs/" }],
  },
  {
    id: "algo-b-design-monotonic-stack",
    category: "algo",
    topic: "数据结构设计",
    difficulty: 1,
    tags: ["单调栈", "单调队列", "滑动窗口"],
    question: "单调栈和单调队列分别在什么题型里出现，模板怎么记",
    answer: "两者都是提前丢掉不可能成为答案的元素。单调栈解决找左边或右边第一个更大、更小的元素：遍历时把栈顶不满足单调性的元素弹出，弹出的那一刻就确定了它的下一个更大元素。单调队列解决滑动窗口最值：队列存下标，队首过期就弹出，新元素入队前把队尾比它小的都弹掉，队首始终是窗口最大值，用双端队列实现。\n- 时间 O(n)：每个元素最多进出栈或队列一次。\n- 空间 O(n)：最坏情况所有下标都留在栈或队列里。\n易错点：栈里存下标而不是值，才能算距离、判断是否出窗口；判断队首过期要用下标之差，不要用值比较；求下一个更大元素从左往右扫，求前一个更大元素可以反向扫或边扫边记录。\n```python\nstack, res = [], [-1] * len(nums)\nfor i, x in enumerate(nums):\n    while stack and nums[stack[-1]] < x:\n        res[stack.pop()] = x\n    stack.append(i)\n```",
    points: ["单调栈找左右第一个更大更小", "单调队列用双端队列求窗口最值", "存下标才能判断过期与算距离"],
    follow: "要求柱状图中最大矩形面积，单调栈里该维护递增还是递减",
    sources: [{ repo: "hello-algo", path: "docs/chapter_stack_and_queue/" }, { repo: "leetcode-master", path: "problems/" }],
  },
];
